# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_boundary12 import APIBoundary12

class TestAPIBoundary12(unittest.TestCase):
    """APIBoundary12 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIBoundary12:
        """Test APIBoundary12
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIBoundary12`
        """
        model = APIBoundary12()
        if include_optional:
            return APIBoundary12(
                polyline_collection = [
                    schooldigger.models.api_polyline.APIPolyline(
                        polyline_overlay_encoded_points = '', 
                        number_encoded_points = 56, )
                    ],
                polylines = '',
                has_boundary = True
            )
        else:
            return APIBoundary12(
        )
        """

    def testAPIBoundary12(self):
        """Test APIBoundary12"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
