# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.api.schools_api import SchoolsApi


class TestSchoolsApi(unittest.TestCase):
    """SchoolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SchoolsApi()

    def tearDown(self) -> None:
        pass

    def test_get_school(self) -> None:
        """Test case for get_school

        Returns a detailed record for one school
        """
        pass

    def test_search_schools(self) -> None:
        """Test case for search_schools

        Returns a list of schools
        """
        pass


if __name__ == '__main__':
    unittest.main()
