# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v3.0
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_test_score30_percent_tier2 import APITestScore30PercentTier2

class TestAPITestScore30PercentTier2(unittest.TestCase):
    """APITestScore30PercentTier2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APITestScore30PercentTier2:
        """Test APITestScore30PercentTier2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APITestScore30PercentTier2`
        """
        model = APITestScore30PercentTier2()
        if include_optional:
            return APITestScore30PercentTier2(
                status = '',
                value = 1.337,
                low = 1.337,
                high = 1.337
            )
        else:
            return APITestScore30PercentTier2(
        )
        """

    def testAPITestScore30PercentTier2(self):
        """Test APITestScore30PercentTier2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
