# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_district_summary21 import APIDistrictSummary21

class TestAPIDistrictSummary21(unittest.TestCase):
    """APIDistrictSummary21 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIDistrictSummary21:
        """Test APIDistrictSummary21
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIDistrictSummary21`
        """
        model = APIDistrictSummary21()
        if include_optional:
            return APIDistrictSummary21(
                district_id = '',
                district_name = '',
                phone = '',
                url = '',
                address = schooldigger.models.api_location.APILocation(
                    lat_long = schooldigger.models.api_lat_long.APILatLong(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    street = '', 
                    city = '', 
                    state = '', 
                    state_full = '', 
                    zip = '', 
                    zip4 = '', 
                    city_url = '', 
                    zip_url = '', 
                    html = '', ),
                location_is_within_boundary = True,
                has_boundary = True,
                distance = 1.337,
                is_within_boundary = True,
                county = schooldigger.models.api_county.APICounty(
                    county_name = '', 
                    county_url = '', ),
                low_grade = '',
                high_grade = '',
                number_total_schools = 56,
                number_primary_schools = 56,
                number_middle_schools = 56,
                number_high_schools = 56,
                number_alternative_schools = 56,
                rank_history = [
                    schooldigger.models.apilea_rank_history.APILEARankHistory(
                        year = 56, 
                        rank = 56, 
                        rank_of = 56, 
                        rank_stars = 56, 
                        rank_statewide_percentage = 1.337, 
                        rank_score = 1.337, )
                    ],
                district_yearly_details = [
                    schooldigger.models.apilea_yearly_detail.APILEAYearlyDetail(
                        year = 56, 
                        number_of_students = 56, 
                        number_of_special_ed_students = 56, 
                        number_of_english_language_learner_students = 56, 
                        number_of_teachers = 1.337, 
                        number_of_teachers_pk = 1.337, 
                        number_of_teachers_k = 1.337, 
                        number_of_teachers_elementary = 1.337, 
                        number_of_teachers_secondary = 1.337, 
                        number_of_aids = 1.337, 
                        number_of_coords_supervisors = 1.337, 
                        number_of_guidance_elem = 1.337, 
                        number_of_guidance_secondary = 1.337, 
                        number_of_guidance_total = 1.337, 
                        number_of_librarians = 1.337, 
                        number_of_library_staff = 1.337, 
                        number_of_lea_administrators = 1.337, 
                        number_of_lea_support_staff = 1.337, 
                        number_of_school_administrators = 1.337, 
                        number_of_school_admin_support_staff = 1.337, 
                        number_of_student_support_staff = 1.337, 
                        number_of_other_support_staff = 1.337, )
                    ]
            )
        else:
            return APIDistrictSummary21(
        )
        """

    def testAPIDistrictSummary21(self):
        """Test APIDistrictSummary21"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
