# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_polyline import APIPolyline

class TestAPIPolyline(unittest.TestCase):
    """APIPolyline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIPolyline:
        """Test APIPolyline
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIPolyline`
        """
        model = APIPolyline()
        if include_optional:
            return APIPolyline(
                polyline_overlay_encoded_points = '',
                number_encoded_points = 56
            )
        else:
            return APIPolyline(
        )
        """

    def testAPIPolyline(self):
        """Test APIPolyline"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
