# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_rank_history import APIRankHistory

class TestAPIRankHistory(unittest.TestCase):
    """APIRankHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIRankHistory:
        """Test APIRankHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIRankHistory`
        """
        model = APIRankHistory()
        if include_optional:
            return APIRankHistory(
                year = 56,
                rank = 56,
                rank_of = 56,
                rank_stars = 56,
                rank_level = '',
                rank_statewide_percentage = 1.337,
                average_standard_score = 1.337
            )
        else:
            return APIRankHistory(
        )
        """

    def testAPIRankHistory(self):
        """Test APIRankHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
