# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v3.0
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_test_score_wrapper30 import APITestScoreWrapper30

class TestAPITestScoreWrapper30(unittest.TestCase):
    """APITestScoreWrapper30 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APITestScoreWrapper30:
        """Test APITestScoreWrapper30
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APITestScoreWrapper30`
        """
        model = APITestScoreWrapper30()
        if include_optional:
            return APITestScoreWrapper30(
                test = '',
                subject = '',
                year = 56,
                grade = '',
                school_test_score = schooldigger.models.api_test_score30.APITestScore30(
                    students_eligible = 56, 
                    students_tested = 56, 
                    mean_scaled_score = 1.337, 
                    percent_met_standard = null, 
                    number_met_standard = 1.337, 
                    num_tier1 = 56, 
                    num_tier2 = 56, 
                    num_tier3 = 56, 
                    num_tier4 = 56, 
                    num_tier5 = 56, 
                    percent_tier1 = null, 
                    percent_tier2 = null, 
                    percent_tier3 = null, 
                    percent_tier4 = null, 
                    percent_tier5 = null, ),
                district_test_score = schooldigger.models.api_test_score30.APITestScore30(
                    students_eligible = 56, 
                    students_tested = 56, 
                    mean_scaled_score = 1.337, 
                    percent_met_standard = null, 
                    number_met_standard = 1.337, 
                    num_tier1 = 56, 
                    num_tier2 = 56, 
                    num_tier3 = 56, 
                    num_tier4 = 56, 
                    num_tier5 = 56, 
                    percent_tier1 = null, 
                    percent_tier2 = null, 
                    percent_tier3 = null, 
                    percent_tier4 = null, 
                    percent_tier5 = null, ),
                state_test_score = schooldigger.models.api_test_score30.APITestScore30(
                    students_eligible = 56, 
                    students_tested = 56, 
                    mean_scaled_score = 1.337, 
                    percent_met_standard = null, 
                    number_met_standard = 1.337, 
                    num_tier1 = 56, 
                    num_tier2 = 56, 
                    num_tier3 = 56, 
                    num_tier4 = 56, 
                    num_tier5 = 56, 
                    percent_tier1 = null, 
                    percent_tier2 = null, 
                    percent_tier3 = null, 
                    percent_tier4 = null, 
                    percent_tier5 = null, ),
                tier1 = '',
                tier2 = '',
                tier3 = '',
                tier4 = '',
                tier5 = ''
            )
        else:
            return APITestScoreWrapper30(
        )
        """

    def testAPITestScoreWrapper30(self):
        """Test APITestScoreWrapper30"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
