# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v3.0
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_reported_percent import APIReportedPercent

class TestAPIReportedPercent(unittest.TestCase):
    """APIReportedPercent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIReportedPercent:
        """Test APIReportedPercent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIReportedPercent`
        """
        model = APIReportedPercent()
        if include_optional:
            return APIReportedPercent(
                status = '',
                value = 1.337,
                low = 1.337,
                high = 1.337
            )
        else:
            return APIReportedPercent(
        )
        """

    def testAPIReportedPercent(self):
        """Test APIReportedPercent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
