# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.apilea_rank_history import APILEARankHistory

class TestAPILEARankHistory(unittest.TestCase):
    """APILEARankHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APILEARankHistory:
        """Test APILEARankHistory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APILEARankHistory`
        """
        model = APILEARankHistory()
        if include_optional:
            return APILEARankHistory(
                year = 56,
                rank = 56,
                rank_of = 56,
                rank_stars = 56,
                rank_statewide_percentage = 1.337,
                rank_score = 1.337
            )
        else:
            return APILEARankHistory(
        )
        """

    def testAPILEARankHistory(self):
        """Test APILEARankHistory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
