# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_test_score_wrapper import APITestScoreWrapper

class TestAPITestScoreWrapper(unittest.TestCase):
    """APITestScoreWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APITestScoreWrapper:
        """Test APITestScoreWrapper
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APITestScoreWrapper`
        """
        model = APITestScoreWrapper()
        if include_optional:
            return APITestScoreWrapper(
                test = '',
                subject = '',
                year = 56,
                grade = '',
                school_test_score = schooldigger.models.api_test_score.APITestScore(
                    students_eligible = 56, 
                    students_tested = 56, 
                    mean_scaled_score = 1.337, 
                    percent_met_standard = 1.337, 
                    number_met_standard = 1.337, 
                    num_tier1 = 56, 
                    num_tier2 = 56, 
                    num_tier3 = 56, 
                    num_tier4 = 56, 
                    num_tier5 = 56, 
                    percent_tier1 = 1.337, 
                    percent_tier2 = 1.337, 
                    percent_tier3 = 1.337, 
                    percent_tier4 = 1.337, 
                    percent_tier5 = 1.337, ),
                district_test_score = schooldigger.models.api_test_score.APITestScore(
                    students_eligible = 56, 
                    students_tested = 56, 
                    mean_scaled_score = 1.337, 
                    percent_met_standard = 1.337, 
                    number_met_standard = 1.337, 
                    num_tier1 = 56, 
                    num_tier2 = 56, 
                    num_tier3 = 56, 
                    num_tier4 = 56, 
                    num_tier5 = 56, 
                    percent_tier1 = 1.337, 
                    percent_tier2 = 1.337, 
                    percent_tier3 = 1.337, 
                    percent_tier4 = 1.337, 
                    percent_tier5 = 1.337, ),
                state_test_score = schooldigger.models.api_test_score.APITestScore(
                    students_eligible = 56, 
                    students_tested = 56, 
                    mean_scaled_score = 1.337, 
                    percent_met_standard = 1.337, 
                    number_met_standard = 1.337, 
                    num_tier1 = 56, 
                    num_tier2 = 56, 
                    num_tier3 = 56, 
                    num_tier4 = 56, 
                    num_tier5 = 56, 
                    percent_tier1 = 1.337, 
                    percent_tier2 = 1.337, 
                    percent_tier3 = 1.337, 
                    percent_tier4 = 1.337, 
                    percent_tier5 = 1.337, ),
                tier1 = '',
                tier2 = '',
                tier3 = '',
                tier4 = '',
                tier5 = ''
            )
        else:
            return APITestScoreWrapper(
        )
        """

    def testAPITestScoreWrapper(self):
        """Test APITestScoreWrapper"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
