# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_location import APILocation

class TestAPILocation(unittest.TestCase):
    """APILocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APILocation:
        """Test APILocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APILocation`
        """
        model = APILocation()
        if include_optional:
            return APILocation(
                lat_long = schooldigger.models.api_lat_long.APILatLong(
                    latitude = 1.337, 
                    longitude = 1.337, ),
                street = '',
                city = '',
                state = '',
                state_full = '',
                zip = '',
                zip4 = '',
                city_url = '',
                zip_url = '',
                html = ''
            )
        else:
            return APILocation(
        )
        """

    def testAPILocation(self):
        """Test APILocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
