# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.api.rankings_api import RankingsApi


class TestRankingsApi(unittest.TestCase):
    """RankingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RankingsApi()

    def tearDown(self) -> None:
        pass

    def test_get_district_rankings(self) -> None:
        """Test case for get_district_rankings

        Returns a SchoolDigger district ranking list
        """
        pass

    def test_get_school_rankings(self) -> None:
        """Test case for get_school_rankings

        Returns a SchoolDigger school ranking list
        """
        pass


if __name__ == '__main__':
    unittest.main()
