# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_district_full21 import APIDistrictFull21

class TestAPIDistrictFull21(unittest.TestCase):
    """APIDistrictFull21 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIDistrictFull21:
        """Test APIDistrictFull21
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIDistrictFull21`
        """
        model = APIDistrictFull21()
        if include_optional:
            return APIDistrictFull21(
                district_id = '',
                district_name = '',
                phone = '',
                url = '',
                address = schooldigger.models.api_location.APILocation(
                    lat_long = schooldigger.models.api_lat_long.APILatLong(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    street = '', 
                    city = '', 
                    state = '', 
                    state_full = '', 
                    zip = '', 
                    zip4 = '', 
                    city_url = '', 
                    zip_url = '', 
                    html = '', ),
                low_grade = '',
                high_grade = '',
                number_total_schools = 56,
                number_primary_schools = 56,
                number_middle_schools = 56,
                number_high_schools = 56,
                number_alternative_schools = 56,
                boundary = schooldigger.models.api_boundary12.APIBoundary12(
                    polyline_collection = [
                        schooldigger.models.api_polyline.APIPolyline(
                            polyline_overlay_encoded_points = '', 
                            number_encoded_points = 56, )
                        ], 
                    polylines = '', 
                    has_boundary = True, ),
                finance = [
                    schooldigger.models.api_school_finance.APISchoolFinance(
                        year = 56, 
                        spending_per_student = 1.337, 
                        spending_federal_personnel = 1.337, 
                        spending_federal_non_personnel = 1.337, 
                        spending_state_local_personnel = 1.337, 
                        spending_state_local_non_personnel = 1.337, 
                        spending_per_student_federal = 1.337, 
                        spending_per_student_state_local = 1.337, )
                    ],
                graduation_rates = [
                    schooldigger.models.api_graduation_rate.APIGraduationRate(
                        year = 56, 
                        school_graduation_rate = 1.337, 
                        district_graduation_rate = 1.337, 
                        state_graduation_rate = 1.337, )
                    ],
                dropout_rates = [
                    schooldigger.models.api_dropout_rate.APIDropoutRate(
                        year = 56, 
                        school_dropout_rate = 1.337, 
                        district_dropout_rate = 1.337, 
                        state_dropout_rate = 1.337, )
                    ],
                chronic_absenteeism_rates = [
                    schooldigger.models.api_chronic_absenteeism_rate.APIChronicAbsenteeismRate(
                        year = 56, 
                        school_chronic_absenteeism_rate = 1.337, 
                        district_chronic_absenteeism_rate = 1.337, 
                        state_chronic_absenteeism_rate = 1.337, )
                    ],
                is_within_boundary = True,
                county = schooldigger.models.api_county.APICounty(
                    county_name = '', 
                    county_url = '', ),
                rank_history = [
                    schooldigger.models.apilea_rank_history.APILEARankHistory(
                        year = 56, 
                        rank = 56, 
                        rank_of = 56, 
                        rank_stars = 56, 
                        rank_statewide_percentage = 1.337, 
                        rank_score = 1.337, )
                    ],
                district_yearly_details = [
                    schooldigger.models.apilea_yearly_detail.APILEAYearlyDetail(
                        year = 56, 
                        number_of_students = 56, 
                        number_of_special_ed_students = 56, 
                        number_of_english_language_learner_students = 56, 
                        number_of_teachers = 1.337, 
                        number_of_teachers_pk = 1.337, 
                        number_of_teachers_k = 1.337, 
                        number_of_teachers_elementary = 1.337, 
                        number_of_teachers_secondary = 1.337, 
                        number_of_aids = 1.337, 
                        number_of_coords_supervisors = 1.337, 
                        number_of_guidance_elem = 1.337, 
                        number_of_guidance_secondary = 1.337, 
                        number_of_guidance_total = 1.337, 
                        number_of_librarians = 1.337, 
                        number_of_library_staff = 1.337, 
                        number_of_lea_administrators = 1.337, 
                        number_of_lea_support_staff = 1.337, 
                        number_of_school_administrators = 1.337, 
                        number_of_school_admin_support_staff = 1.337, 
                        number_of_student_support_staff = 1.337, 
                        number_of_other_support_staff = 1.337, )
                    ],
                test_scores = [
                    schooldigger.models.api_test_score_wrapper.APITestScoreWrapper(
                        test = '', 
                        subject = '', 
                        year = 56, 
                        grade = '', 
                        school_test_score = schooldigger.models.api_test_score.APITestScore(
                            students_eligible = 56, 
                            students_tested = 56, 
                            mean_scaled_score = 1.337, 
                            percent_met_standard = 1.337, 
                            number_met_standard = 1.337, 
                            num_tier1 = 56, 
                            num_tier2 = 56, 
                            num_tier3 = 56, 
                            num_tier4 = 56, 
                            num_tier5 = 56, 
                            percent_tier1 = 1.337, 
                            percent_tier2 = 1.337, 
                            percent_tier3 = 1.337, 
                            percent_tier4 = 1.337, 
                            percent_tier5 = 1.337, ), 
                        district_test_score = schooldigger.models.api_test_score.APITestScore(
                            students_eligible = 56, 
                            students_tested = 56, 
                            mean_scaled_score = 1.337, 
                            percent_met_standard = 1.337, 
                            number_met_standard = 1.337, 
                            num_tier1 = 56, 
                            num_tier2 = 56, 
                            num_tier3 = 56, 
                            num_tier4 = 56, 
                            num_tier5 = 56, 
                            percent_tier1 = 1.337, 
                            percent_tier2 = 1.337, 
                            percent_tier3 = 1.337, 
                            percent_tier4 = 1.337, 
                            percent_tier5 = 1.337, ), 
                        state_test_score = , 
                        tier1 = '', 
                        tier2 = '', 
                        tier3 = '', 
                        tier4 = '', 
                        tier5 = '', )
                    ]
            )
        else:
            return APIDistrictFull21(
        )
        """

    def testAPIDistrictFull21(self):
        """Test APIDistrictFull21"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
