# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_school_full22 import APISchoolFull22

class TestAPISchoolFull22(unittest.TestCase):
    """APISchoolFull22 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APISchoolFull22:
        """Test APISchoolFull22
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APISchoolFull22`
        """
        model = APISchoolFull22()
        if include_optional:
            return APISchoolFull22(
                schoolid = '',
                school_name = '',
                phone = '',
                url = '',
                url_school_digger = '',
                url_compare_school_digger = '',
                address = schooldigger.models.api_location.APILocation(
                    lat_long = schooldigger.models.api_lat_long.APILatLong(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    street = '', 
                    city = '', 
                    state = '', 
                    state_full = '', 
                    zip = '', 
                    zip4 = '', 
                    city_url = '', 
                    zip_url = '', 
                    html = '', ),
                locale = '',
                low_grade = '',
                high_grade = '',
                school_level = '',
                is_charter_school = '',
                is_magnet_school = '',
                is_virtual_school = '',
                is_title_i_school = '',
                is_title_i_schoolwide_school = '',
                is_private = True,
                private_days = 56,
                private_hours = 1.337,
                private_has_library = True,
                private_coed = '',
                private_orientation = '',
                nces_private_school_id = '',
                district = schooldigger.models.api_district_sum.APIDistrictSum(
                    district_id = '', 
                    district_name = '', 
                    url = '', 
                    rank_url = '', ),
                county = schooldigger.models.api_county.APICounty(
                    county_name = '', 
                    county_url = '', ),
                reviews = [
                    schooldigger.models.api_school_review.APISchoolReview(
                        submit_date = '', 
                        number_of_stars = 56, 
                        comment = '', 
                        submitted_by = '', )
                    ],
                finance = [
                    schooldigger.models.api_school_finance.APISchoolFinance(
                        year = 56, 
                        spending_per_student = 1.337, 
                        spending_federal_personnel = 1.337, 
                        spending_federal_non_personnel = 1.337, 
                        spending_state_local_personnel = 1.337, 
                        spending_state_local_non_personnel = 1.337, 
                        spending_per_student_federal = 1.337, 
                        spending_per_student_state_local = 1.337, )
                    ],
                graduation_rates = [
                    schooldigger.models.api_graduation_rate.APIGraduationRate(
                        year = 56, 
                        school_graduation_rate = 1.337, 
                        district_graduation_rate = 1.337, 
                        state_graduation_rate = 1.337, )
                    ],
                dropout_rates = [
                    schooldigger.models.api_dropout_rate.APIDropoutRate(
                        year = 56, 
                        school_dropout_rate = 1.337, 
                        district_dropout_rate = 1.337, 
                        state_dropout_rate = 1.337, )
                    ],
                chronic_absenteeism_rates = [
                    schooldigger.models.api_chronic_absenteeism_rate.APIChronicAbsenteeismRate(
                        year = 56, 
                        school_chronic_absenteeism_rate = 1.337, 
                        district_chronic_absenteeism_rate = 1.337, 
                        state_chronic_absenteeism_rate = 1.337, )
                    ],
                rank_history = [
                    schooldigger.models.api_rank_history.APIRankHistory(
                        year = 56, 
                        rank = 56, 
                        rank_of = 56, 
                        rank_stars = 56, 
                        rank_level = '', 
                        rank_statewide_percentage = 1.337, 
                        average_standard_score = 1.337, )
                    ],
                rank_movement = 56,
                test_scores = [
                    schooldigger.models.api_test_score_wrapper.APITestScoreWrapper(
                        test = '', 
                        subject = '', 
                        year = 56, 
                        grade = '', 
                        school_test_score = schooldigger.models.api_test_score.APITestScore(
                            students_eligible = 56, 
                            students_tested = 56, 
                            mean_scaled_score = 1.337, 
                            percent_met_standard = 1.337, 
                            number_met_standard = 1.337, 
                            num_tier1 = 56, 
                            num_tier2 = 56, 
                            num_tier3 = 56, 
                            num_tier4 = 56, 
                            num_tier5 = 56, 
                            percent_tier1 = 1.337, 
                            percent_tier2 = 1.337, 
                            percent_tier3 = 1.337, 
                            percent_tier4 = 1.337, 
                            percent_tier5 = 1.337, ), 
                        district_test_score = schooldigger.models.api_test_score.APITestScore(
                            students_eligible = 56, 
                            students_tested = 56, 
                            mean_scaled_score = 1.337, 
                            percent_met_standard = 1.337, 
                            number_met_standard = 1.337, 
                            num_tier1 = 56, 
                            num_tier2 = 56, 
                            num_tier3 = 56, 
                            num_tier4 = 56, 
                            num_tier5 = 56, 
                            percent_tier1 = 1.337, 
                            percent_tier2 = 1.337, 
                            percent_tier3 = 1.337, 
                            percent_tier4 = 1.337, 
                            percent_tier5 = 1.337, ), 
                        state_test_score = , 
                        tier1 = '', 
                        tier2 = '', 
                        tier3 = '', 
                        tier4 = '', 
                        tier5 = '', )
                    ],
                school_yearly_details = [
                    schooldigger.models.api_yearly_demographics.APIYearlyDemographics(
                        year = 56, 
                        number_of_students = 56, 
                        percent_free_disc_lunch = 1.337, 
                        percentof_african_american_students = 1.337, 
                        percentof_asian_students = 1.337, 
                        percentof_hispanic_students = 1.337, 
                        percentof_indian_students = 1.337, 
                        percentof_pacific_islander_students = 1.337, 
                        percentof_white_students = 1.337, 
                        percentof_two_or_more_race_students = 1.337, 
                        percentof_unspecified_race_students = 1.337, 
                        teachers_fulltime = 1.337, 
                        pupil_teacher_ratio = 1.337, 
                        numberof_african_american_students = 56, 
                        numberof_asian_students = 56, 
                        numberof_hispanic_students = 56, 
                        numberof_indian_students = 56, 
                        numberof_pacific_islander_students = 56, 
                        numberof_white_students = 56, 
                        numberof_two_or_more_race_students = 56, 
                        numberof_unspecified_race_students = 56, )
                    ]
            )
        else:
            return APISchoolFull22(
        )
        """

    def testAPISchoolFull22(self):
        """Test APISchoolFull22"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
