# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v3.0
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_test_score30_percent_met_standard import APITestScore30PercentMetStandard

class TestAPITestScore30PercentMetStandard(unittest.TestCase):
    """APITestScore30PercentMetStandard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APITestScore30PercentMetStandard:
        """Test APITestScore30PercentMetStandard
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APITestScore30PercentMetStandard`
        """
        model = APITestScore30PercentMetStandard()
        if include_optional:
            return APITestScore30PercentMetStandard(
                status = '',
                value = 1.337,
                low = 1.337,
                high = 1.337
            )
        else:
            return APITestScore30PercentMetStandard(
        )
        """

    def testAPITestScore30PercentMetStandard(self):
        """Test APITestScore30PercentMetStandard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
