# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.api.autocomplete_api import AutocompleteApi


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutocompleteApi()

    def tearDown(self) -> None:
        pass

    def test_autocomplete_districts(self) -> None:
        """Test case for autocomplete_districts

        Returns a simple and quick list of districts for use in a client-typed autocomplete
        """
        pass

    def test_autocomplete_schools(self) -> None:
        """Test case for autocomplete_schools

        Returns a simple and quick list of schools for use in a client-typed autocomplete
        """
        pass


if __name__ == '__main__':
    unittest.main()
