# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_school_finance import APISchoolFinance

class TestAPISchoolFinance(unittest.TestCase):
    """APISchoolFinance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APISchoolFinance:
        """Test APISchoolFinance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APISchoolFinance`
        """
        model = APISchoolFinance()
        if include_optional:
            return APISchoolFinance(
                year = 56,
                spending_per_student = 1.337,
                spending_federal_personnel = 1.337,
                spending_federal_non_personnel = 1.337,
                spending_state_local_personnel = 1.337,
                spending_state_local_non_personnel = 1.337,
                spending_per_student_federal = 1.337,
                spending_per_student_state_local = 1.337
            )
        else:
            return APISchoolFinance(
        )
        """

    def testAPISchoolFinance(self):
        """Test APISchoolFinance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
