# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.api.districts_api import DistrictsApi


class TestDistrictsApi(unittest.TestCase):
    """DistrictsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DistrictsApi()

    def tearDown(self) -> None:
        pass

    def test_get_district(self) -> None:
        """Test case for get_district

        Returns a detailed record for one district
        """
        pass

    def test_search_districts(self) -> None:
        """Test case for search_districts

        Returns a list of districts
        """
        pass


if __name__ == '__main__':
    unittest.main()
