# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_lat_long import APILatLong

class TestAPILatLong(unittest.TestCase):
    """APILatLong unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APILatLong:
        """Test APILatLong
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APILatLong`
        """
        model = APILatLong()
        if include_optional:
            return APILatLong(
                latitude = 1.337,
                longitude = 1.337
            )
        else:
            return APILatLong(
        )
        """

    def testAPILatLong(self):
        """Test APILatLong"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
