# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_autocomplete_school_result23 import APIAutocompleteSchoolResult23

class TestAPIAutocompleteSchoolResult23(unittest.TestCase):
    """APIAutocompleteSchoolResult23 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIAutocompleteSchoolResult23:
        """Test APIAutocompleteSchoolResult23
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIAutocompleteSchoolResult23`
        """
        model = APIAutocompleteSchoolResult23()
        if include_optional:
            return APIAutocompleteSchoolResult23(
                school_matches = [
                    schooldigger.models.api_school_ac23.APISchoolAC23(
                        schoolid = '', 
                        school_name = '', 
                        city = '', 
                        state = '', 
                        zip = '', 
                        school_level = '', 
                        low_grade = '', 
                        high_grade = '', 
                        latitude = 1.337, 
                        longitude = 1.337, 
                        rank = 56, 
                        rank_of = 56, 
                        rank_stars = 56, 
                        nces_private_school_id = '', )
                    ]
            )
        else:
            return APIAutocompleteSchoolResult23(
        )
        """

    def testAPIAutocompleteSchoolResult23(self):
        """Test APIAutocompleteSchoolResult23"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
