# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_yearly_demographics import APIYearlyDemographics

class TestAPIYearlyDemographics(unittest.TestCase):
    """APIYearlyDemographics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIYearlyDemographics:
        """Test APIYearlyDemographics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIYearlyDemographics`
        """
        model = APIYearlyDemographics()
        if include_optional:
            return APIYearlyDemographics(
                year = 56,
                number_of_students = 56,
                percent_free_disc_lunch = 1.337,
                percentof_african_american_students = 1.337,
                percentof_asian_students = 1.337,
                percentof_hispanic_students = 1.337,
                percentof_indian_students = 1.337,
                percentof_pacific_islander_students = 1.337,
                percentof_white_students = 1.337,
                percentof_two_or_more_race_students = 1.337,
                percentof_unspecified_race_students = 1.337,
                teachers_fulltime = 1.337,
                pupil_teacher_ratio = 1.337,
                numberof_african_american_students = 56,
                numberof_asian_students = 56,
                numberof_hispanic_students = 56,
                numberof_indian_students = 56,
                numberof_pacific_islander_students = 56,
                numberof_white_students = 56,
                numberof_two_or_more_race_students = 56,
                numberof_unspecified_race_students = 56
            )
        else:
            return APIYearlyDemographics(
        )
        """

    def testAPIYearlyDemographics(self):
        """Test APIYearlyDemographics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
