# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_test_score import APITestScore

class TestAPITestScore(unittest.TestCase):
    """APITestScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APITestScore:
        """Test APITestScore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APITestScore`
        """
        model = APITestScore()
        if include_optional:
            return APITestScore(
                students_eligible = 56,
                students_tested = 56,
                mean_scaled_score = 1.337,
                percent_met_standard = 1.337,
                number_met_standard = 1.337,
                num_tier1 = 56,
                num_tier2 = 56,
                num_tier3 = 56,
                num_tier4 = 56,
                num_tier5 = 56,
                percent_tier1 = 1.337,
                percent_tier2 = 1.337,
                percent_tier3 = 1.337,
                percent_tier4 = 1.337,
                percent_tier5 = 1.337
            )
        else:
            return APITestScore(
        )
        """

    def testAPITestScore(self):
        """Test APITestScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
