# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from schooldigger.models.api_district_ac import APIDistrictAC

class TestAPIDistrictAC(unittest.TestCase):
    """APIDistrictAC unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APIDistrictAC:
        """Test APIDistrictAC
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APIDistrictAC`
        """
        model = APIDistrictAC()
        if include_optional:
            return APIDistrictAC(
                districtid = '',
                district_name = '',
                city = '',
                state = '',
                zip = '',
                low_grade = '',
                high_grade = '',
                latitude = 1.337,
                longitude = 1.337,
                has_boundary = True,
                rank = 56,
                rank_of = 56,
                rank_stars = 56
            )
        else:
            return APIDistrictAC(
        )
        """

    def testAPIDistrictAC(self):
        """Test APIDistrictAC"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
