"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Optional, Union
from typing_extensions import Annotated
from schooldigger.models.api_autocomplete_district_result import APIAutocompleteDistrictResult
from schooldigger.models.api_autocomplete_school_result23 import APIAutocompleteSchoolResult23

from schooldigger.api_client import ApiClient, RequestSerialized
from schooldigger.api_response import ApiResponse
from schooldigger.rest import RESTResponseType


class AutocompleteApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def autocomplete_districts(
        self,
        q: Annotated[Optional[StrictStr], Field(description="Search term for autocomplete (e.g. 'Lincol') (required)")] = None,
        st: Annotated[Optional[StrictStr], Field(description="Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)")] = None,
        box_latitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        box_longitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        box_latitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        box_longitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        return_count: Annotated[Optional[StrictInt], Field(description="Number of districts to return. Valid values: 1-20. (default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> APIAutocompleteDistrictResult:
        """Returns a simple and quick list of districts for use in a client-typed autocomplete

        

        :param q: Search term for autocomplete (e.g. 'Lincol') (required)
        :type q: str
        :param st: Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)
        :type st: str
        :param box_latitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_latitude_nw: float
        :param box_longitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_longitude_nw: float
        :param box_latitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_latitude_se: float
        :param box_longitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_longitude_se: float
        :param return_count: Number of districts to return. Valid values: 1-20. (default: 10)
        :type return_count: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._autocomplete_districts_serialize(
            q=q,
            st=st,
            box_latitude_nw=box_latitude_nw,
            box_longitude_nw=box_longitude_nw,
            box_latitude_se=box_latitude_se,
            box_longitude_se=box_longitude_se,
            return_count=return_count,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APIAutocompleteDistrictResult",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def autocomplete_districts_with_http_info(
        self,
        q: Annotated[Optional[StrictStr], Field(description="Search term for autocomplete (e.g. 'Lincol') (required)")] = None,
        st: Annotated[Optional[StrictStr], Field(description="Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)")] = None,
        box_latitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        box_longitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        box_latitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        box_longitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        return_count: Annotated[Optional[StrictInt], Field(description="Number of districts to return. Valid values: 1-20. (default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[APIAutocompleteDistrictResult]:
        """Returns a simple and quick list of districts for use in a client-typed autocomplete

        

        :param q: Search term for autocomplete (e.g. 'Lincol') (required)
        :type q: str
        :param st: Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)
        :type st: str
        :param box_latitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_latitude_nw: float
        :param box_longitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_longitude_nw: float
        :param box_latitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_latitude_se: float
        :param box_longitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_longitude_se: float
        :param return_count: Number of districts to return. Valid values: 1-20. (default: 10)
        :type return_count: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._autocomplete_districts_serialize(
            q=q,
            st=st,
            box_latitude_nw=box_latitude_nw,
            box_longitude_nw=box_longitude_nw,
            box_latitude_se=box_latitude_se,
            box_longitude_se=box_longitude_se,
            return_count=return_count,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APIAutocompleteDistrictResult",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def autocomplete_districts_without_preload_content(
        self,
        q: Annotated[Optional[StrictStr], Field(description="Search term for autocomplete (e.g. 'Lincol') (required)")] = None,
        st: Annotated[Optional[StrictStr], Field(description="Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)")] = None,
        box_latitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        box_longitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        box_latitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        box_longitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)")] = None,
        return_count: Annotated[Optional[StrictInt], Field(description="Number of districts to return. Valid values: 1-20. (default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a simple and quick list of districts for use in a client-typed autocomplete

        

        :param q: Search term for autocomplete (e.g. 'Lincol') (required)
        :type q: str
        :param st: Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)
        :type st: str
        :param box_latitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_latitude_nw: float
        :param box_longitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_longitude_nw: float
        :param box_latitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_latitude_se: float
        :param box_longitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise API levels only.)
        :type box_longitude_se: float
        :param return_count: Number of districts to return. Valid values: 1-20. (default: 10)
        :type return_count: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._autocomplete_districts_serialize(
            q=q,
            st=st,
            box_latitude_nw=box_latitude_nw,
            box_longitude_nw=box_longitude_nw,
            box_latitude_se=box_latitude_se,
            box_longitude_se=box_longitude_se,
            return_count=return_count,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APIAutocompleteDistrictResult",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _autocomplete_districts_serialize(
        self,
        q,
        st,
        box_latitude_nw,
        box_longitude_nw,
        box_latitude_se,
        box_longitude_se,
        return_count,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if q is not None:
            
            _query_params.append(('q', q))
            
        if st is not None:
            
            _query_params.append(('st', st))
            
        if box_latitude_nw is not None:
            
            _query_params.append(('boxLatitudeNW', box_latitude_nw))
            
        if box_longitude_nw is not None:
            
            _query_params.append(('boxLongitudeNW', box_longitude_nw))
            
        if box_latitude_se is not None:
            
            _query_params.append(('boxLatitudeSE', box_latitude_se))
            
        if box_longitude_se is not None:
            
            _query_params.append(('boxLongitudeSE', box_longitude_se))
            
        if return_count is not None:
            
            _query_params.append(('returnCount', return_count))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'appID', 
            'appKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2.4/autocomplete/districts',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def autocomplete_schools(
        self,
        q: Annotated[Optional[StrictStr], Field(description="Search term for autocomplete (e.g. 'Lincol') (required)")] = None,
        q_search_city_state_name: Annotated[Optional[StrictBool], Field(description="Extend the search term to include city and state (e.g. 'Lincoln el paso' matches Lincoln Middle School in El Paso) (optional)")] = None,
        st: Annotated[Optional[StrictStr], Field(description="Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)")] = None,
        level: Annotated[Optional[StrictStr], Field(description="Search for schools at this level only. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Private' (optional - leave blank to search for all schools)")] = None,
        district_id: Annotated[Optional[StrictStr], Field(description="Search within SchoolDigger District ID (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_latitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_longitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_latitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_longitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        return_count: Annotated[Optional[StrictInt], Field(description="Number of schools to return. Valid values: 1-20. (default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> APIAutocompleteSchoolResult23:
        """Returns a simple and quick list of schools for use in a client-typed autocomplete

        

        :param q: Search term for autocomplete (e.g. 'Lincol') (required)
        :type q: str
        :param q_search_city_state_name: Extend the search term to include city and state (e.g. 'Lincoln el paso' matches Lincoln Middle School in El Paso) (optional)
        :type q_search_city_state_name: bool
        :param st: Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)
        :type st: str
        :param level: Search for schools at this level only. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Private' (optional - leave blank to search for all schools)
        :type level: str
        :param district_id: Search within SchoolDigger District ID (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type district_id: str
        :param box_latitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_latitude_nw: float
        :param box_longitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_longitude_nw: float
        :param box_latitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_latitude_se: float
        :param box_longitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_longitude_se: float
        :param return_count: Number of schools to return. Valid values: 1-20. (default: 10)
        :type return_count: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._autocomplete_schools_serialize(
            q=q,
            q_search_city_state_name=q_search_city_state_name,
            st=st,
            level=level,
            district_id=district_id,
            box_latitude_nw=box_latitude_nw,
            box_longitude_nw=box_longitude_nw,
            box_latitude_se=box_latitude_se,
            box_longitude_se=box_longitude_se,
            return_count=return_count,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APIAutocompleteSchoolResult23",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def autocomplete_schools_with_http_info(
        self,
        q: Annotated[Optional[StrictStr], Field(description="Search term for autocomplete (e.g. 'Lincol') (required)")] = None,
        q_search_city_state_name: Annotated[Optional[StrictBool], Field(description="Extend the search term to include city and state (e.g. 'Lincoln el paso' matches Lincoln Middle School in El Paso) (optional)")] = None,
        st: Annotated[Optional[StrictStr], Field(description="Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)")] = None,
        level: Annotated[Optional[StrictStr], Field(description="Search for schools at this level only. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Private' (optional - leave blank to search for all schools)")] = None,
        district_id: Annotated[Optional[StrictStr], Field(description="Search within SchoolDigger District ID (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_latitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_longitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_latitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_longitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        return_count: Annotated[Optional[StrictInt], Field(description="Number of schools to return. Valid values: 1-20. (default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[APIAutocompleteSchoolResult23]:
        """Returns a simple and quick list of schools for use in a client-typed autocomplete

        

        :param q: Search term for autocomplete (e.g. 'Lincol') (required)
        :type q: str
        :param q_search_city_state_name: Extend the search term to include city and state (e.g. 'Lincoln el paso' matches Lincoln Middle School in El Paso) (optional)
        :type q_search_city_state_name: bool
        :param st: Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)
        :type st: str
        :param level: Search for schools at this level only. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Private' (optional - leave blank to search for all schools)
        :type level: str
        :param district_id: Search within SchoolDigger District ID (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type district_id: str
        :param box_latitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_latitude_nw: float
        :param box_longitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_longitude_nw: float
        :param box_latitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_latitude_se: float
        :param box_longitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_longitude_se: float
        :param return_count: Number of schools to return. Valid values: 1-20. (default: 10)
        :type return_count: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._autocomplete_schools_serialize(
            q=q,
            q_search_city_state_name=q_search_city_state_name,
            st=st,
            level=level,
            district_id=district_id,
            box_latitude_nw=box_latitude_nw,
            box_longitude_nw=box_longitude_nw,
            box_latitude_se=box_latitude_se,
            box_longitude_se=box_longitude_se,
            return_count=return_count,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APIAutocompleteSchoolResult23",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def autocomplete_schools_without_preload_content(
        self,
        q: Annotated[Optional[StrictStr], Field(description="Search term for autocomplete (e.g. 'Lincol') (required)")] = None,
        q_search_city_state_name: Annotated[Optional[StrictBool], Field(description="Extend the search term to include city and state (e.g. 'Lincoln el paso' matches Lincoln Middle School in El Paso) (optional)")] = None,
        st: Annotated[Optional[StrictStr], Field(description="Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)")] = None,
        level: Annotated[Optional[StrictStr], Field(description="Search for schools at this level only. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Private' (optional - leave blank to search for all schools)")] = None,
        district_id: Annotated[Optional[StrictStr], Field(description="Search within SchoolDigger District ID (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_latitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_longitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_latitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        box_longitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)")] = None,
        return_count: Annotated[Optional[StrictInt], Field(description="Number of schools to return. Valid values: 1-20. (default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a simple and quick list of schools for use in a client-typed autocomplete

        

        :param q: Search term for autocomplete (e.g. 'Lincol') (required)
        :type q: str
        :param q_search_city_state_name: Extend the search term to include city and state (e.g. 'Lincoln el paso' matches Lincoln Middle School in El Paso) (optional)
        :type q_search_city_state_name: bool
        :param st: Two character state (e.g. 'CA') (optional -- leave blank to search entire U.S.)
        :type st: str
        :param level: Search for schools at this level only. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Private' (optional - leave blank to search for all schools)
        :type level: str
        :param district_id: Search within SchoolDigger District ID (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type district_id: str
        :param box_latitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_latitude_nw: float
        :param box_longitude_nw: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_longitude_nw: float
        :param box_latitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_latitude_se: float
        :param box_longitude_se: Search within a 'box' defined by (BoxLatitudeNW/BoxLongitudeNW) to (BoxLongitudeSE/BoxLatitudeSE) (optional. Pro, Enterprise, and Autocomplete Pro levels only.)
        :type box_longitude_se: float
        :param return_count: Number of schools to return. Valid values: 1-20. (default: 10)
        :type return_count: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._autocomplete_schools_serialize(
            q=q,
            q_search_city_state_name=q_search_city_state_name,
            st=st,
            level=level,
            district_id=district_id,
            box_latitude_nw=box_latitude_nw,
            box_longitude_nw=box_longitude_nw,
            box_latitude_se=box_latitude_se,
            box_longitude_se=box_longitude_se,
            return_count=return_count,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APIAutocompleteSchoolResult23",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _autocomplete_schools_serialize(
        self,
        q,
        q_search_city_state_name,
        st,
        level,
        district_id,
        box_latitude_nw,
        box_longitude_nw,
        box_latitude_se,
        box_longitude_se,
        return_count,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if q is not None:
            
            _query_params.append(('q', q))
            
        if q_search_city_state_name is not None:
            
            _query_params.append(('qSearchCityStateName', q_search_city_state_name))
            
        if st is not None:
            
            _query_params.append(('st', st))
            
        if level is not None:
            
            _query_params.append(('level', level))
            
        if district_id is not None:
            
            _query_params.append(('districtID', district_id))
            
        if box_latitude_nw is not None:
            
            _query_params.append(('boxLatitudeNW', box_latitude_nw))
            
        if box_longitude_nw is not None:
            
            _query_params.append(('boxLongitudeNW', box_longitude_nw))
            
        if box_latitude_se is not None:
            
            _query_params.append(('boxLatitudeSE', box_latitude_se))
            
        if box_longitude_se is not None:
            
            _query_params.append(('boxLongitudeSE', box_longitude_se))
            
        if return_count is not None:
            
            _query_params.append(('returnCount', return_count))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'appID', 
            'appKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2.4/autocomplete/schools',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


