"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from schooldigger.models.api_district_list_rank21 import APIDistrictListRank21
from schooldigger.models.api_school_list_rank21 import APISchoolListRank21

from schooldigger.api_client import ApiClient, RequestSerialized
from schooldigger.api_response import ApiResponse
from schooldigger.rest import RESTResponseType


class RankingsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_district_rankings(
        self,
        st: Annotated[StrictStr, Field(description="Two character state (e.g. 'CA')")],
        year: Annotated[Optional[StrictInt], Field(description="The ranking year (leave blank for most recent year)")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number to retrieve (optional, default: 1)")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of districts to retrieve on a page (50 max) (optional, default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> APIDistrictListRank21:
        """Returns a SchoolDigger district ranking list


        :param st: Two character state (e.g. 'CA') (required)
        :type st: str
        :param year: The ranking year (leave blank for most recent year)
        :type year: int
        :param page: Page number to retrieve (optional, default: 1)
        :type page: int
        :param per_page: Number of districts to retrieve on a page (50 max) (optional, default: 10)
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_district_rankings_serialize(
            st=st,
            year=year,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APIDistrictListRank21",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_district_rankings_with_http_info(
        self,
        st: Annotated[StrictStr, Field(description="Two character state (e.g. 'CA')")],
        year: Annotated[Optional[StrictInt], Field(description="The ranking year (leave blank for most recent year)")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number to retrieve (optional, default: 1)")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of districts to retrieve on a page (50 max) (optional, default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[APIDistrictListRank21]:
        """Returns a SchoolDigger district ranking list


        :param st: Two character state (e.g. 'CA') (required)
        :type st: str
        :param year: The ranking year (leave blank for most recent year)
        :type year: int
        :param page: Page number to retrieve (optional, default: 1)
        :type page: int
        :param per_page: Number of districts to retrieve on a page (50 max) (optional, default: 10)
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_district_rankings_serialize(
            st=st,
            year=year,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APIDistrictListRank21",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_district_rankings_without_preload_content(
        self,
        st: Annotated[StrictStr, Field(description="Two character state (e.g. 'CA')")],
        year: Annotated[Optional[StrictInt], Field(description="The ranking year (leave blank for most recent year)")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number to retrieve (optional, default: 1)")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of districts to retrieve on a page (50 max) (optional, default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a SchoolDigger district ranking list


        :param st: Two character state (e.g. 'CA') (required)
        :type st: str
        :param year: The ranking year (leave blank for most recent year)
        :type year: int
        :param page: Page number to retrieve (optional, default: 1)
        :type page: int
        :param per_page: Number of districts to retrieve on a page (50 max) (optional, default: 10)
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_district_rankings_serialize(
            st=st,
            year=year,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APIDistrictListRank21",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_district_rankings_serialize(
        self,
        st,
        year,
        page,
        per_page,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if st is not None:
            _path_params['st'] = st
        # process the query parameters
        if year is not None:
            
            _query_params.append(('year', year))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('perPage', per_page))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'appID', 
            'appKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2.3/rankings/districts/{st}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_school_rankings(
        self,
        st: Annotated[StrictStr, Field(description="Two character state (e.g. 'CA')")],
        year: Annotated[Optional[StrictInt], Field(description="The ranking year (leave blank for most recent year)")] = None,
        level: Annotated[Optional[StrictStr], Field(description="Level of ranking: 'Elementary', 'Middle', or 'High'")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number to retrieve (optional, default: 1)")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of schools to retrieve on a page (50 max) (optional, default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> APISchoolListRank21:
        """Returns a SchoolDigger school ranking list


        :param st: Two character state (e.g. 'CA') (required)
        :type st: str
        :param year: The ranking year (leave blank for most recent year)
        :type year: int
        :param level: Level of ranking: 'Elementary', 'Middle', or 'High'
        :type level: str
        :param page: Page number to retrieve (optional, default: 1)
        :type page: int
        :param per_page: Number of schools to retrieve on a page (50 max) (optional, default: 10)
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_school_rankings_serialize(
            st=st,
            year=year,
            level=level,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APISchoolListRank21",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_school_rankings_with_http_info(
        self,
        st: Annotated[StrictStr, Field(description="Two character state (e.g. 'CA')")],
        year: Annotated[Optional[StrictInt], Field(description="The ranking year (leave blank for most recent year)")] = None,
        level: Annotated[Optional[StrictStr], Field(description="Level of ranking: 'Elementary', 'Middle', or 'High'")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number to retrieve (optional, default: 1)")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of schools to retrieve on a page (50 max) (optional, default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[APISchoolListRank21]:
        """Returns a SchoolDigger school ranking list


        :param st: Two character state (e.g. 'CA') (required)
        :type st: str
        :param year: The ranking year (leave blank for most recent year)
        :type year: int
        :param level: Level of ranking: 'Elementary', 'Middle', or 'High'
        :type level: str
        :param page: Page number to retrieve (optional, default: 1)
        :type page: int
        :param per_page: Number of schools to retrieve on a page (50 max) (optional, default: 10)
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_school_rankings_serialize(
            st=st,
            year=year,
            level=level,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APISchoolListRank21",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_school_rankings_without_preload_content(
        self,
        st: Annotated[StrictStr, Field(description="Two character state (e.g. 'CA')")],
        year: Annotated[Optional[StrictInt], Field(description="The ranking year (leave blank for most recent year)")] = None,
        level: Annotated[Optional[StrictStr], Field(description="Level of ranking: 'Elementary', 'Middle', or 'High'")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number to retrieve (optional, default: 1)")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of schools to retrieve on a page (50 max) (optional, default: 10)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a SchoolDigger school ranking list


        :param st: Two character state (e.g. 'CA') (required)
        :type st: str
        :param year: The ranking year (leave blank for most recent year)
        :type year: int
        :param level: Level of ranking: 'Elementary', 'Middle', or 'High'
        :type level: str
        :param page: Page number to retrieve (optional, default: 1)
        :type page: int
        :param per_page: Number of schools to retrieve on a page (50 max) (optional, default: 10)
        :type per_page: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_school_rankings_serialize(
            st=st,
            year=year,
            level=level,
            page=page,
            per_page=per_page,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APISchoolListRank21",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_school_rankings_serialize(
        self,
        st,
        year,
        level,
        page,
        per_page,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if st is not None:
            _path_params['st'] = st
        # process the query parameters
        if year is not None:
            
            _query_params.append(('year', year))
            
        if level is not None:
            
            _query_params.append(('level', level))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('perPage', per_page))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'appID', 
            'appKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2.3/rankings/schools/{st}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


