"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Optional, Union
from typing_extensions import Annotated
from schooldigger.models.api_school_full22 import APISchoolFull22
from schooldigger.models.api_school_list22 import APISchoolList22

from schooldigger.api_client import ApiClient, RequestSerialized
from schooldigger.api_response import ApiResponse
from schooldigger.rest import RESTResponseType


class SchoolsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_school(
        self,
        id: Annotated[StrictStr, Field(description="The 12 digit School ID (e.g. 064215006903)")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> APISchoolFull22:
        """Returns a detailed record for one school

        Retrieve a school record from the SchoolDigger database

        :param id: The 12 digit School ID (e.g. 064215006903) (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_school_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APISchoolFull22",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_school_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="The 12 digit School ID (e.g. 064215006903)")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[APISchoolFull22]:
        """Returns a detailed record for one school

        Retrieve a school record from the SchoolDigger database

        :param id: The 12 digit School ID (e.g. 064215006903) (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_school_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APISchoolFull22",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_school_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="The 12 digit School ID (e.g. 064215006903)")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a detailed record for one school

        Retrieve a school record from the SchoolDigger database

        :param id: The 12 digit School ID (e.g. 064215006903) (required)
        :type id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_school_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APISchoolFull22",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_school_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'appID', 
            'appKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2.4/schools/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def search_schools(
        self,
        st: Annotated[Optional[StrictStr], Field(description="Two character state (e.g. 'CA') - optional if you supply a location search (nearLatitude/nearLongitude, nearAddress, or box coordinates) or a districtID; required otherwise. Location searches without 'st' may return schools from multiple states.")] = None,
        q: Annotated[Optional[StrictStr], Field(description="Search term - note: will match school name or city (optional)")] = None,
        q_search_school_name_only: Annotated[Optional[StrictBool], Field(description="For parameter 'q', only search school names instead of school and city (optional)")] = None,
        district_id: Annotated[Optional[StrictStr], Field(description="Search for schools within this district (7 digit district id) (optional)")] = None,
        level: Annotated[Optional[StrictStr], Field(description="Search for schools at this level. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Public', 'Private' (optional). 'Public' returns all Elementary, Middle, High and Alternative schools")] = None,
        city: Annotated[Optional[StrictStr], Field(description="Search for schools in this city (optional)")] = None,
        zip: Annotated[Optional[StrictStr], Field(description="Search for schools in this 5-digit zip code (optional)")] = None,
        is_magnet: Annotated[Optional[StrictBool], Field(description="True = return only magnet schools, False = return only non-magnet schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_charter: Annotated[Optional[StrictBool], Field(description="True = return only charter schools, False = return only non-charter schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_virtual: Annotated[Optional[StrictBool], Field(description="True = return only virtual schools, False = return only non-virtual schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_title_i: Annotated[Optional[StrictBool], Field(description="True = return only Title I schools, False = return only non-Title I schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_title_i_schoolwide: Annotated[Optional[StrictBool], Field(description="True = return only Title I school-wide schools, False = return only non-Title I school-wide schools (optional) (Pro, Enterprise API levels only)")] = None,
        near_latitude: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. 44.982560) (optional) (Pro, Enterprise API levels only.)")] = None,
        near_longitude: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. -124.289185) (optional) (Pro, Enterprise API levels only.)")] = None,
        near_address: Annotated[Optional[StrictStr], Field(description="Search for schools within (distanceMiles) of this address. Example: '123 Main St. AnyTown CA 90001' (optional) (Pro, Enterprise API level only) IMPORTANT NOTE: If you have the lat/long of the address, use nearLatitude and nearLongitude instead for much faster response times")] = None,
        distance_miles: Annotated[Optional[StrictInt], Field(description="Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (Default 5 miles) (optional) (Pro, Enterprise API levels only)")] = None,
        box_latitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        box_longitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        box_latitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        box_longitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number to retrieve (optional, default: 1)")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of schools to retrieve on a page (50 max) (optional, default: 10)")] = None,
        sort_by: Annotated[Optional[StrictStr], Field(description="Sort list. Values are: schoolname, distance, rank. For descending order, precede with '-' i.e. -schoolname (optional, default: schoolname)")] = None,
        include_unranked_schools_in_rank_sort: Annotated[Optional[StrictBool], Field(description="If sortBy is 'rank', this boolean determines if schools with no rank are included in the result (optional, default: false)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> APISchoolList22:
        """Returns a list of schools

        Search the SchoolDigger database for schools. You may use any combination of criteria as query parameters. New in v2.4: location searches (nearLatitude/nearLongitude, nearAddress, or box coordinates) no longer require 'st' and may return schools from more than one state.

        :param st: Two character state (e.g. 'CA') - optional if you supply a location search (nearLatitude/nearLongitude, nearAddress, or box coordinates) or a districtID; required otherwise. Location searches without 'st' may return schools from multiple states.
        :type st: str
        :param q: Search term - note: will match school name or city (optional)
        :type q: str
        :param q_search_school_name_only: For parameter 'q', only search school names instead of school and city (optional)
        :type q_search_school_name_only: bool
        :param district_id: Search for schools within this district (7 digit district id) (optional)
        :type district_id: str
        :param level: Search for schools at this level. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Public', 'Private' (optional). 'Public' returns all Elementary, Middle, High and Alternative schools
        :type level: str
        :param city: Search for schools in this city (optional)
        :type city: str
        :param zip: Search for schools in this 5-digit zip code (optional)
        :type zip: str
        :param is_magnet: True = return only magnet schools, False = return only non-magnet schools (optional) (Pro, Enterprise API levels only)
        :type is_magnet: bool
        :param is_charter: True = return only charter schools, False = return only non-charter schools (optional) (Pro, Enterprise API levels only)
        :type is_charter: bool
        :param is_virtual: True = return only virtual schools, False = return only non-virtual schools (optional) (Pro, Enterprise API levels only)
        :type is_virtual: bool
        :param is_title_i: True = return only Title I schools, False = return only non-Title I schools (optional) (Pro, Enterprise API levels only)
        :type is_title_i: bool
        :param is_title_i_schoolwide: True = return only Title I school-wide schools, False = return only non-Title I school-wide schools (optional) (Pro, Enterprise API levels only)
        :type is_title_i_schoolwide: bool
        :param near_latitude: Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. 44.982560) (optional) (Pro, Enterprise API levels only.)
        :type near_latitude: float
        :param near_longitude: Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. -124.289185) (optional) (Pro, Enterprise API levels only.)
        :type near_longitude: float
        :param near_address: Search for schools within (distanceMiles) of this address. Example: '123 Main St. AnyTown CA 90001' (optional) (Pro, Enterprise API level only) IMPORTANT NOTE: If you have the lat/long of the address, use nearLatitude and nearLongitude instead for much faster response times
        :type near_address: str
        :param distance_miles: Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (Default 5 miles) (optional) (Pro, Enterprise API levels only)
        :type distance_miles: int
        :param box_latitude_nw: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_latitude_nw: float
        :param box_longitude_nw: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_longitude_nw: float
        :param box_latitude_se: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_latitude_se: float
        :param box_longitude_se: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_longitude_se: float
        :param page: Page number to retrieve (optional, default: 1)
        :type page: int
        :param per_page: Number of schools to retrieve on a page (50 max) (optional, default: 10)
        :type per_page: int
        :param sort_by: Sort list. Values are: schoolname, distance, rank. For descending order, precede with '-' i.e. -schoolname (optional, default: schoolname)
        :type sort_by: str
        :param include_unranked_schools_in_rank_sort: If sortBy is 'rank', this boolean determines if schools with no rank are included in the result (optional, default: false)
        :type include_unranked_schools_in_rank_sort: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_schools_serialize(
            st=st,
            q=q,
            q_search_school_name_only=q_search_school_name_only,
            district_id=district_id,
            level=level,
            city=city,
            zip=zip,
            is_magnet=is_magnet,
            is_charter=is_charter,
            is_virtual=is_virtual,
            is_title_i=is_title_i,
            is_title_i_schoolwide=is_title_i_schoolwide,
            near_latitude=near_latitude,
            near_longitude=near_longitude,
            near_address=near_address,
            distance_miles=distance_miles,
            box_latitude_nw=box_latitude_nw,
            box_longitude_nw=box_longitude_nw,
            box_latitude_se=box_latitude_se,
            box_longitude_se=box_longitude_se,
            page=page,
            per_page=per_page,
            sort_by=sort_by,
            include_unranked_schools_in_rank_sort=include_unranked_schools_in_rank_sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APISchoolList22",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_schools_with_http_info(
        self,
        st: Annotated[Optional[StrictStr], Field(description="Two character state (e.g. 'CA') - optional if you supply a location search (nearLatitude/nearLongitude, nearAddress, or box coordinates) or a districtID; required otherwise. Location searches without 'st' may return schools from multiple states.")] = None,
        q: Annotated[Optional[StrictStr], Field(description="Search term - note: will match school name or city (optional)")] = None,
        q_search_school_name_only: Annotated[Optional[StrictBool], Field(description="For parameter 'q', only search school names instead of school and city (optional)")] = None,
        district_id: Annotated[Optional[StrictStr], Field(description="Search for schools within this district (7 digit district id) (optional)")] = None,
        level: Annotated[Optional[StrictStr], Field(description="Search for schools at this level. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Public', 'Private' (optional). 'Public' returns all Elementary, Middle, High and Alternative schools")] = None,
        city: Annotated[Optional[StrictStr], Field(description="Search for schools in this city (optional)")] = None,
        zip: Annotated[Optional[StrictStr], Field(description="Search for schools in this 5-digit zip code (optional)")] = None,
        is_magnet: Annotated[Optional[StrictBool], Field(description="True = return only magnet schools, False = return only non-magnet schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_charter: Annotated[Optional[StrictBool], Field(description="True = return only charter schools, False = return only non-charter schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_virtual: Annotated[Optional[StrictBool], Field(description="True = return only virtual schools, False = return only non-virtual schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_title_i: Annotated[Optional[StrictBool], Field(description="True = return only Title I schools, False = return only non-Title I schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_title_i_schoolwide: Annotated[Optional[StrictBool], Field(description="True = return only Title I school-wide schools, False = return only non-Title I school-wide schools (optional) (Pro, Enterprise API levels only)")] = None,
        near_latitude: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. 44.982560) (optional) (Pro, Enterprise API levels only.)")] = None,
        near_longitude: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. -124.289185) (optional) (Pro, Enterprise API levels only.)")] = None,
        near_address: Annotated[Optional[StrictStr], Field(description="Search for schools within (distanceMiles) of this address. Example: '123 Main St. AnyTown CA 90001' (optional) (Pro, Enterprise API level only) IMPORTANT NOTE: If you have the lat/long of the address, use nearLatitude and nearLongitude instead for much faster response times")] = None,
        distance_miles: Annotated[Optional[StrictInt], Field(description="Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (Default 5 miles) (optional) (Pro, Enterprise API levels only)")] = None,
        box_latitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        box_longitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        box_latitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        box_longitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number to retrieve (optional, default: 1)")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of schools to retrieve on a page (50 max) (optional, default: 10)")] = None,
        sort_by: Annotated[Optional[StrictStr], Field(description="Sort list. Values are: schoolname, distance, rank. For descending order, precede with '-' i.e. -schoolname (optional, default: schoolname)")] = None,
        include_unranked_schools_in_rank_sort: Annotated[Optional[StrictBool], Field(description="If sortBy is 'rank', this boolean determines if schools with no rank are included in the result (optional, default: false)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[APISchoolList22]:
        """Returns a list of schools

        Search the SchoolDigger database for schools. You may use any combination of criteria as query parameters. New in v2.4: location searches (nearLatitude/nearLongitude, nearAddress, or box coordinates) no longer require 'st' and may return schools from more than one state.

        :param st: Two character state (e.g. 'CA') - optional if you supply a location search (nearLatitude/nearLongitude, nearAddress, or box coordinates) or a districtID; required otherwise. Location searches without 'st' may return schools from multiple states.
        :type st: str
        :param q: Search term - note: will match school name or city (optional)
        :type q: str
        :param q_search_school_name_only: For parameter 'q', only search school names instead of school and city (optional)
        :type q_search_school_name_only: bool
        :param district_id: Search for schools within this district (7 digit district id) (optional)
        :type district_id: str
        :param level: Search for schools at this level. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Public', 'Private' (optional). 'Public' returns all Elementary, Middle, High and Alternative schools
        :type level: str
        :param city: Search for schools in this city (optional)
        :type city: str
        :param zip: Search for schools in this 5-digit zip code (optional)
        :type zip: str
        :param is_magnet: True = return only magnet schools, False = return only non-magnet schools (optional) (Pro, Enterprise API levels only)
        :type is_magnet: bool
        :param is_charter: True = return only charter schools, False = return only non-charter schools (optional) (Pro, Enterprise API levels only)
        :type is_charter: bool
        :param is_virtual: True = return only virtual schools, False = return only non-virtual schools (optional) (Pro, Enterprise API levels only)
        :type is_virtual: bool
        :param is_title_i: True = return only Title I schools, False = return only non-Title I schools (optional) (Pro, Enterprise API levels only)
        :type is_title_i: bool
        :param is_title_i_schoolwide: True = return only Title I school-wide schools, False = return only non-Title I school-wide schools (optional) (Pro, Enterprise API levels only)
        :type is_title_i_schoolwide: bool
        :param near_latitude: Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. 44.982560) (optional) (Pro, Enterprise API levels only.)
        :type near_latitude: float
        :param near_longitude: Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. -124.289185) (optional) (Pro, Enterprise API levels only.)
        :type near_longitude: float
        :param near_address: Search for schools within (distanceMiles) of this address. Example: '123 Main St. AnyTown CA 90001' (optional) (Pro, Enterprise API level only) IMPORTANT NOTE: If you have the lat/long of the address, use nearLatitude and nearLongitude instead for much faster response times
        :type near_address: str
        :param distance_miles: Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (Default 5 miles) (optional) (Pro, Enterprise API levels only)
        :type distance_miles: int
        :param box_latitude_nw: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_latitude_nw: float
        :param box_longitude_nw: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_longitude_nw: float
        :param box_latitude_se: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_latitude_se: float
        :param box_longitude_se: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_longitude_se: float
        :param page: Page number to retrieve (optional, default: 1)
        :type page: int
        :param per_page: Number of schools to retrieve on a page (50 max) (optional, default: 10)
        :type per_page: int
        :param sort_by: Sort list. Values are: schoolname, distance, rank. For descending order, precede with '-' i.e. -schoolname (optional, default: schoolname)
        :type sort_by: str
        :param include_unranked_schools_in_rank_sort: If sortBy is 'rank', this boolean determines if schools with no rank are included in the result (optional, default: false)
        :type include_unranked_schools_in_rank_sort: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_schools_serialize(
            st=st,
            q=q,
            q_search_school_name_only=q_search_school_name_only,
            district_id=district_id,
            level=level,
            city=city,
            zip=zip,
            is_magnet=is_magnet,
            is_charter=is_charter,
            is_virtual=is_virtual,
            is_title_i=is_title_i,
            is_title_i_schoolwide=is_title_i_schoolwide,
            near_latitude=near_latitude,
            near_longitude=near_longitude,
            near_address=near_address,
            distance_miles=distance_miles,
            box_latitude_nw=box_latitude_nw,
            box_longitude_nw=box_longitude_nw,
            box_latitude_se=box_latitude_se,
            box_longitude_se=box_longitude_se,
            page=page,
            per_page=per_page,
            sort_by=sort_by,
            include_unranked_schools_in_rank_sort=include_unranked_schools_in_rank_sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APISchoolList22",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_schools_without_preload_content(
        self,
        st: Annotated[Optional[StrictStr], Field(description="Two character state (e.g. 'CA') - optional if you supply a location search (nearLatitude/nearLongitude, nearAddress, or box coordinates) or a districtID; required otherwise. Location searches without 'st' may return schools from multiple states.")] = None,
        q: Annotated[Optional[StrictStr], Field(description="Search term - note: will match school name or city (optional)")] = None,
        q_search_school_name_only: Annotated[Optional[StrictBool], Field(description="For parameter 'q', only search school names instead of school and city (optional)")] = None,
        district_id: Annotated[Optional[StrictStr], Field(description="Search for schools within this district (7 digit district id) (optional)")] = None,
        level: Annotated[Optional[StrictStr], Field(description="Search for schools at this level. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Public', 'Private' (optional). 'Public' returns all Elementary, Middle, High and Alternative schools")] = None,
        city: Annotated[Optional[StrictStr], Field(description="Search for schools in this city (optional)")] = None,
        zip: Annotated[Optional[StrictStr], Field(description="Search for schools in this 5-digit zip code (optional)")] = None,
        is_magnet: Annotated[Optional[StrictBool], Field(description="True = return only magnet schools, False = return only non-magnet schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_charter: Annotated[Optional[StrictBool], Field(description="True = return only charter schools, False = return only non-charter schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_virtual: Annotated[Optional[StrictBool], Field(description="True = return only virtual schools, False = return only non-virtual schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_title_i: Annotated[Optional[StrictBool], Field(description="True = return only Title I schools, False = return only non-Title I schools (optional) (Pro, Enterprise API levels only)")] = None,
        is_title_i_schoolwide: Annotated[Optional[StrictBool], Field(description="True = return only Title I school-wide schools, False = return only non-Title I school-wide schools (optional) (Pro, Enterprise API levels only)")] = None,
        near_latitude: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. 44.982560) (optional) (Pro, Enterprise API levels only.)")] = None,
        near_longitude: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. -124.289185) (optional) (Pro, Enterprise API levels only.)")] = None,
        near_address: Annotated[Optional[StrictStr], Field(description="Search for schools within (distanceMiles) of this address. Example: '123 Main St. AnyTown CA 90001' (optional) (Pro, Enterprise API level only) IMPORTANT NOTE: If you have the lat/long of the address, use nearLatitude and nearLongitude instead for much faster response times")] = None,
        distance_miles: Annotated[Optional[StrictInt], Field(description="Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (Default 5 miles) (optional) (Pro, Enterprise API levels only)")] = None,
        box_latitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        box_longitude_nw: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        box_latitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        box_longitude_se: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)")] = None,
        page: Annotated[Optional[StrictInt], Field(description="Page number to retrieve (optional, default: 1)")] = None,
        per_page: Annotated[Optional[StrictInt], Field(description="Number of schools to retrieve on a page (50 max) (optional, default: 10)")] = None,
        sort_by: Annotated[Optional[StrictStr], Field(description="Sort list. Values are: schoolname, distance, rank. For descending order, precede with '-' i.e. -schoolname (optional, default: schoolname)")] = None,
        include_unranked_schools_in_rank_sort: Annotated[Optional[StrictBool], Field(description="If sortBy is 'rank', this boolean determines if schools with no rank are included in the result (optional, default: false)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Returns a list of schools

        Search the SchoolDigger database for schools. You may use any combination of criteria as query parameters. New in v2.4: location searches (nearLatitude/nearLongitude, nearAddress, or box coordinates) no longer require 'st' and may return schools from more than one state.

        :param st: Two character state (e.g. 'CA') - optional if you supply a location search (nearLatitude/nearLongitude, nearAddress, or box coordinates) or a districtID; required otherwise. Location searches without 'st' may return schools from multiple states.
        :type st: str
        :param q: Search term - note: will match school name or city (optional)
        :type q: str
        :param q_search_school_name_only: For parameter 'q', only search school names instead of school and city (optional)
        :type q_search_school_name_only: bool
        :param district_id: Search for schools within this district (7 digit district id) (optional)
        :type district_id: str
        :param level: Search for schools at this level. Valid values: 'Elementary', 'Middle', 'High', 'Alt', 'Public', 'Private' (optional). 'Public' returns all Elementary, Middle, High and Alternative schools
        :type level: str
        :param city: Search for schools in this city (optional)
        :type city: str
        :param zip: Search for schools in this 5-digit zip code (optional)
        :type zip: str
        :param is_magnet: True = return only magnet schools, False = return only non-magnet schools (optional) (Pro, Enterprise API levels only)
        :type is_magnet: bool
        :param is_charter: True = return only charter schools, False = return only non-charter schools (optional) (Pro, Enterprise API levels only)
        :type is_charter: bool
        :param is_virtual: True = return only virtual schools, False = return only non-virtual schools (optional) (Pro, Enterprise API levels only)
        :type is_virtual: bool
        :param is_title_i: True = return only Title I schools, False = return only non-Title I schools (optional) (Pro, Enterprise API levels only)
        :type is_title_i: bool
        :param is_title_i_schoolwide: True = return only Title I school-wide schools, False = return only non-Title I school-wide schools (optional) (Pro, Enterprise API levels only)
        :type is_title_i_schoolwide: bool
        :param near_latitude: Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. 44.982560) (optional) (Pro, Enterprise API levels only.)
        :type near_latitude: float
        :param near_longitude: Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (e.g. -124.289185) (optional) (Pro, Enterprise API levels only.)
        :type near_longitude: float
        :param near_address: Search for schools within (distanceMiles) of this address. Example: '123 Main St. AnyTown CA 90001' (optional) (Pro, Enterprise API level only) IMPORTANT NOTE: If you have the lat/long of the address, use nearLatitude and nearLongitude instead for much faster response times
        :type near_address: str
        :param distance_miles: Search for schools within (distanceMiles) of (nearLatitude)/(nearLongitude) (Default 5 miles) (optional) (Pro, Enterprise API levels only)
        :type distance_miles: int
        :param box_latitude_nw: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_latitude_nw: float
        :param box_longitude_nw: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_longitude_nw: float
        :param box_latitude_se: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_latitude_se: float
        :param box_longitude_se: Search for schools within a 'box' defined by (boxLatitudeNW/boxLongitudeNW) to (boxLongitudeSE/boxLatitudeSE) (optional)
        :type box_longitude_se: float
        :param page: Page number to retrieve (optional, default: 1)
        :type page: int
        :param per_page: Number of schools to retrieve on a page (50 max) (optional, default: 10)
        :type per_page: int
        :param sort_by: Sort list. Values are: schoolname, distance, rank. For descending order, precede with '-' i.e. -schoolname (optional, default: schoolname)
        :type sort_by: str
        :param include_unranked_schools_in_rank_sort: If sortBy is 'rank', this boolean determines if schools with no rank are included in the result (optional, default: false)
        :type include_unranked_schools_in_rank_sort: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_schools_serialize(
            st=st,
            q=q,
            q_search_school_name_only=q_search_school_name_only,
            district_id=district_id,
            level=level,
            city=city,
            zip=zip,
            is_magnet=is_magnet,
            is_charter=is_charter,
            is_virtual=is_virtual,
            is_title_i=is_title_i,
            is_title_i_schoolwide=is_title_i_schoolwide,
            near_latitude=near_latitude,
            near_longitude=near_longitude,
            near_address=near_address,
            distance_miles=distance_miles,
            box_latitude_nw=box_latitude_nw,
            box_longitude_nw=box_longitude_nw,
            box_latitude_se=box_latitude_se,
            box_longitude_se=box_longitude_se,
            page=page,
            per_page=per_page,
            sort_by=sort_by,
            include_unranked_schools_in_rank_sort=include_unranked_schools_in_rank_sort,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "APISchoolList22",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_schools_serialize(
        self,
        st,
        q,
        q_search_school_name_only,
        district_id,
        level,
        city,
        zip,
        is_magnet,
        is_charter,
        is_virtual,
        is_title_i,
        is_title_i_schoolwide,
        near_latitude,
        near_longitude,
        near_address,
        distance_miles,
        box_latitude_nw,
        box_longitude_nw,
        box_latitude_se,
        box_longitude_se,
        page,
        per_page,
        sort_by,
        include_unranked_schools_in_rank_sort,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if st is not None:
            
            _query_params.append(('st', st))
            
        if q is not None:
            
            _query_params.append(('q', q))
            
        if q_search_school_name_only is not None:
            
            _query_params.append(('qSearchSchoolNameOnly', q_search_school_name_only))
            
        if district_id is not None:
            
            _query_params.append(('districtID', district_id))
            
        if level is not None:
            
            _query_params.append(('level', level))
            
        if city is not None:
            
            _query_params.append(('city', city))
            
        if zip is not None:
            
            _query_params.append(('zip', zip))
            
        if is_magnet is not None:
            
            _query_params.append(('isMagnet', is_magnet))
            
        if is_charter is not None:
            
            _query_params.append(('isCharter', is_charter))
            
        if is_virtual is not None:
            
            _query_params.append(('isVirtual', is_virtual))
            
        if is_title_i is not None:
            
            _query_params.append(('isTitleI', is_title_i))
            
        if is_title_i_schoolwide is not None:
            
            _query_params.append(('isTitleISchoolwide', is_title_i_schoolwide))
            
        if near_latitude is not None:
            
            _query_params.append(('nearLatitude', near_latitude))
            
        if near_longitude is not None:
            
            _query_params.append(('nearLongitude', near_longitude))
            
        if near_address is not None:
            
            _query_params.append(('nearAddress', near_address))
            
        if distance_miles is not None:
            
            _query_params.append(('distanceMiles', distance_miles))
            
        if box_latitude_nw is not None:
            
            _query_params.append(('boxLatitudeNW', box_latitude_nw))
            
        if box_longitude_nw is not None:
            
            _query_params.append(('boxLongitudeNW', box_longitude_nw))
            
        if box_latitude_se is not None:
            
            _query_params.append(('boxLatitudeSE', box_latitude_se))
            
        if box_longitude_se is not None:
            
            _query_params.append(('boxLongitudeSE', box_longitude_se))
            
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('perPage', per_page))
            
        if sort_by is not None:
            
            _query_params.append(('sortBy', sort_by))
            
        if include_unranked_schools_in_rank_sort is not None:
            
            _query_params.append(('includeUnrankedSchoolsInRankSort', include_unranked_schools_in_rank_sort))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'appID', 
            'appKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v2.4/schools',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


