# coding: utf-8

# flake8: noqa

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AutocompleteApi",
    "DistrictsApi",
    "RankingsApi",
    "SchoolsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "APIAutocompleteDistrictResult",
    "APIAutocompleteSchoolResult23",
    "APIBoundary12",
    "APIChronicAbsenteeismRate",
    "APICounty",
    "APIDistrictAC",
    "APIDistrictFull21",
    "APIDistrictList21",
    "APIDistrictListRank21",
    "APIDistrictSum",
    "APIDistrictSummary21",
    "APIDropoutRate",
    "APIGraduationRate",
    "APILEARankHistory",
    "APILEAYearlyDetail",
    "APILatLong",
    "APILocation",
    "APIPolyline",
    "APIRankHistory",
    "APISchoolAC23",
    "APISchoolFinance",
    "APISchoolFull22",
    "APISchoolList22",
    "APISchoolListRank21",
    "APISchoolReview",
    "APISchoolSummary21",
    "APISchoolSummary22",
    "APITestScore",
    "APITestScoreWrapper",
    "APIYearlyDemographics",
]

# import apis into sdk package
from schooldigger.api.autocomplete_api import AutocompleteApi as AutocompleteApi
from schooldigger.api.districts_api import DistrictsApi as DistrictsApi
from schooldigger.api.rankings_api import RankingsApi as RankingsApi
from schooldigger.api.schools_api import SchoolsApi as SchoolsApi

# import ApiClient
from schooldigger.api_response import ApiResponse as ApiResponse
from schooldigger.api_client import ApiClient as ApiClient
from schooldigger.configuration import Configuration as Configuration
from schooldigger.exceptions import OpenApiException as OpenApiException
from schooldigger.exceptions import ApiTypeError as ApiTypeError
from schooldigger.exceptions import ApiValueError as ApiValueError
from schooldigger.exceptions import ApiKeyError as ApiKeyError
from schooldigger.exceptions import ApiAttributeError as ApiAttributeError
from schooldigger.exceptions import ApiException as ApiException

# import models into sdk package
from schooldigger.models.api_autocomplete_district_result import APIAutocompleteDistrictResult as APIAutocompleteDistrictResult
from schooldigger.models.api_autocomplete_school_result23 import APIAutocompleteSchoolResult23 as APIAutocompleteSchoolResult23
from schooldigger.models.api_boundary12 import APIBoundary12 as APIBoundary12
from schooldigger.models.api_chronic_absenteeism_rate import APIChronicAbsenteeismRate as APIChronicAbsenteeismRate
from schooldigger.models.api_county import APICounty as APICounty
from schooldigger.models.api_district_ac import APIDistrictAC as APIDistrictAC
from schooldigger.models.api_district_full21 import APIDistrictFull21 as APIDistrictFull21
from schooldigger.models.api_district_list21 import APIDistrictList21 as APIDistrictList21
from schooldigger.models.api_district_list_rank21 import APIDistrictListRank21 as APIDistrictListRank21
from schooldigger.models.api_district_sum import APIDistrictSum as APIDistrictSum
from schooldigger.models.api_district_summary21 import APIDistrictSummary21 as APIDistrictSummary21
from schooldigger.models.api_dropout_rate import APIDropoutRate as APIDropoutRate
from schooldigger.models.api_graduation_rate import APIGraduationRate as APIGraduationRate
from schooldigger.models.apilea_rank_history import APILEARankHistory as APILEARankHistory
from schooldigger.models.apilea_yearly_detail import APILEAYearlyDetail as APILEAYearlyDetail
from schooldigger.models.api_lat_long import APILatLong as APILatLong
from schooldigger.models.api_location import APILocation as APILocation
from schooldigger.models.api_polyline import APIPolyline as APIPolyline
from schooldigger.models.api_rank_history import APIRankHistory as APIRankHistory
from schooldigger.models.api_school_ac23 import APISchoolAC23 as APISchoolAC23
from schooldigger.models.api_school_finance import APISchoolFinance as APISchoolFinance
from schooldigger.models.api_school_full22 import APISchoolFull22 as APISchoolFull22
from schooldigger.models.api_school_list22 import APISchoolList22 as APISchoolList22
from schooldigger.models.api_school_list_rank21 import APISchoolListRank21 as APISchoolListRank21
from schooldigger.models.api_school_review import APISchoolReview as APISchoolReview
from schooldigger.models.api_school_summary21 import APISchoolSummary21 as APISchoolSummary21
from schooldigger.models.api_school_summary22 import APISchoolSummary22 as APISchoolSummary22
from schooldigger.models.api_test_score import APITestScore as APITestScore
from schooldigger.models.api_test_score_wrapper import APITestScoreWrapper as APITestScoreWrapper
from schooldigger.models.api_yearly_demographics import APIYearlyDemographics as APIYearlyDemographics

