# coding: utf-8

# flake8: noqa
"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from schooldigger.models.api_autocomplete_district_result import APIAutocompleteDistrictResult
from schooldigger.models.api_autocomplete_school_result23 import APIAutocompleteSchoolResult23
from schooldigger.models.api_boundary12 import APIBoundary12
from schooldigger.models.api_chronic_absenteeism_rate import APIChronicAbsenteeismRate
from schooldigger.models.api_county import APICounty
from schooldigger.models.api_district_ac import APIDistrictAC
from schooldigger.models.api_district_full21 import APIDistrictFull21
from schooldigger.models.api_district_list21 import APIDistrictList21
from schooldigger.models.api_district_list_rank21 import APIDistrictListRank21
from schooldigger.models.api_district_sum import APIDistrictSum
from schooldigger.models.api_district_summary21 import APIDistrictSummary21
from schooldigger.models.api_dropout_rate import APIDropoutRate
from schooldigger.models.api_graduation_rate import APIGraduationRate
from schooldigger.models.apilea_rank_history import APILEARankHistory
from schooldigger.models.apilea_yearly_detail import APILEAYearlyDetail
from schooldigger.models.api_lat_long import APILatLong
from schooldigger.models.api_location import APILocation
from schooldigger.models.api_polyline import APIPolyline
from schooldigger.models.api_rank_history import APIRankHistory
from schooldigger.models.api_school_ac23 import APISchoolAC23
from schooldigger.models.api_school_finance import APISchoolFinance
from schooldigger.models.api_school_full22 import APISchoolFull22
from schooldigger.models.api_school_list22 import APISchoolList22
from schooldigger.models.api_school_list_rank21 import APISchoolListRank21
from schooldigger.models.api_school_review import APISchoolReview
from schooldigger.models.api_school_summary21 import APISchoolSummary21
from schooldigger.models.api_school_summary22 import APISchoolSummary22
from schooldigger.models.api_test_score import APITestScore
from schooldigger.models.api_test_score_wrapper import APITestScoreWrapper
from schooldigger.models.api_yearly_demographics import APIYearlyDemographics

