# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from schooldigger.models.api_county import APICounty
from schooldigger.models.api_district_sum import APIDistrictSum
from schooldigger.models.api_location import APILocation
from schooldigger.models.api_rank_history import APIRankHistory
from schooldigger.models.api_yearly_demographics import APIYearlyDemographics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APISchoolSummary22(BaseModel):
    """
    APISchool2Summary: A summary of a school record. For the full school record, call /schools/{id}
    """ # noqa: E501
    schoolid: Optional[StrictStr] = Field(default=None, description="SchoolDigger School ID Number (12 digits)")
    school_name: Optional[StrictStr] = Field(default=None, description="School name", alias="schoolName")
    phone: Optional[StrictStr] = Field(default=None, description="School phone number")
    url: Optional[StrictStr] = Field(default=None, description="SchoolDigger URL for this school")
    url_compare: Optional[StrictStr] = Field(default=None, description="SchoolDigger URL for comparing this school to nearby schools", alias="urlCompare")
    address: Optional[APILocation] = None
    distance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Distance from nearLatitude/nearLongitude, boundaryLatitude/boundaryLongitude, or boundaryAddress (if supplied)")
    locale: Optional[StrictStr] = Field(default=None, description="NCES Locale of school (https://nces.ed.gov/ccd/rural_locales.asp)")
    low_grade: Optional[StrictStr] = Field(default=None, description="The low grade served by this school (PK = Prekindergarten, K = Kindergarten)", alias="lowGrade")
    high_grade: Optional[StrictStr] = Field(default=None, description="The high grade served by this school", alias="highGrade")
    school_level: Optional[StrictStr] = Field(default=None, description="The level of school (Elementary, Middle, High, Private, Alternative)", alias="schoolLevel")
    is_charter_school: Optional[StrictStr] = Field(default=None, description="Indicates if school is a charter school (Yes/No/n-a)", alias="isCharterSchool")
    is_magnet_school: Optional[StrictStr] = Field(default=None, description="Indicates if school is a magnet school (Yes/No/n-a)", alias="isMagnetSchool")
    is_virtual_school: Optional[StrictStr] = Field(default=None, description="Indicates if school is a virtual school (Yes/No/n-a)", alias="isVirtualSchool")
    is_title_i_school: Optional[StrictStr] = Field(default=None, description="Indicates if school is a Title I school (Yes/No/n-a)", alias="isTitleISchool")
    is_title_i_schoolwide_school: Optional[StrictStr] = Field(default=None, description="Indicates if a school-wide Title I school (Yes/No/n-a)", alias="isTitleISchoolwideSchool")
    district: Optional[APIDistrictSum] = None
    county: Optional[APICounty] = None
    rank_history: Optional[List[APIRankHistory]] = Field(default=None, description="SchoolDigger yearly rank history of the school. To retrieve all years, call /schools/{id}.", alias="rankHistory")
    rank_movement: Optional[StrictInt] = Field(default=None, description="Returns the movement of rank for this school between current and previous year", alias="rankMovement")
    school_yearly_details: Optional[List[APIYearlyDemographics]] = Field(default=None, description="School Yearly metrics. To retrieve all years, call /schools/{id}.", alias="schoolYearlyDetails")
    is_private: Optional[StrictBool] = Field(default=None, description="Indicates if school is a private school (Yes/No)", alias="isPrivate")
    private_days: Optional[StrictInt] = Field(default=None, description="Days in the school year (private schools only)", alias="privateDays")
    private_hours: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Hours in the school day (private schools only)", alias="privateHours")
    private_has_library: Optional[StrictBool] = Field(default=None, description="Indicates if the school has a library (private schools only)", alias="privateHasLibrary")
    private_coed: Optional[StrictStr] = Field(default=None, description="Coed/Boys/Girls (private schools only)", alias="privateCoed")
    private_orientation: Optional[StrictStr] = Field(default=None, description="Affiliation of the school (private schools only)", alias="privateOrientation")
    nces_private_school_id: Optional[StrictStr] = Field(default=None, description="The NCES ID of the school (private schools only)", alias="ncesPrivateSchoolID")
    __properties: ClassVar[List[str]] = ["schoolid", "schoolName", "phone", "url", "urlCompare", "address", "distance", "locale", "lowGrade", "highGrade", "schoolLevel", "isCharterSchool", "isMagnetSchool", "isVirtualSchool", "isTitleISchool", "isTitleISchoolwideSchool", "district", "county", "rankHistory", "rankMovement", "schoolYearlyDetails", "isPrivate", "privateDays", "privateHours", "privateHasLibrary", "privateCoed", "privateOrientation", "ncesPrivateSchoolID"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APISchoolSummary22 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of district
        if self.district:
            _dict['district'] = self.district.to_dict()
        # override the default output from pydantic by calling `to_dict()` of county
        if self.county:
            _dict['county'] = self.county.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in rank_history (list)
        _items = []
        if self.rank_history:
            for _item_rank_history in self.rank_history:
                if _item_rank_history:
                    _items.append(_item_rank_history.to_dict())
            _dict['rankHistory'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in school_yearly_details (list)
        _items = []
        if self.school_yearly_details:
            for _item_school_yearly_details in self.school_yearly_details:
                if _item_school_yearly_details:
                    _items.append(_item_school_yearly_details.to_dict())
            _dict['schoolYearlyDetails'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APISchoolSummary22 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schoolid": obj.get("schoolid"),
            "schoolName": obj.get("schoolName"),
            "phone": obj.get("phone"),
            "url": obj.get("url"),
            "urlCompare": obj.get("urlCompare"),
            "address": APILocation.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "distance": obj.get("distance"),
            "locale": obj.get("locale"),
            "lowGrade": obj.get("lowGrade"),
            "highGrade": obj.get("highGrade"),
            "schoolLevel": obj.get("schoolLevel"),
            "isCharterSchool": obj.get("isCharterSchool"),
            "isMagnetSchool": obj.get("isMagnetSchool"),
            "isVirtualSchool": obj.get("isVirtualSchool"),
            "isTitleISchool": obj.get("isTitleISchool"),
            "isTitleISchoolwideSchool": obj.get("isTitleISchoolwideSchool"),
            "district": APIDistrictSum.from_dict(obj["district"]) if obj.get("district") is not None else None,
            "county": APICounty.from_dict(obj["county"]) if obj.get("county") is not None else None,
            "rankHistory": [APIRankHistory.from_dict(_item) for _item in obj["rankHistory"]] if obj.get("rankHistory") is not None else None,
            "rankMovement": obj.get("rankMovement"),
            "schoolYearlyDetails": [APIYearlyDemographics.from_dict(_item) for _item in obj["schoolYearlyDetails"]] if obj.get("schoolYearlyDetails") is not None else None,
            "isPrivate": obj.get("isPrivate"),
            "privateDays": obj.get("privateDays"),
            "privateHours": obj.get("privateHours"),
            "privateHasLibrary": obj.get("privateHasLibrary"),
            "privateCoed": obj.get("privateCoed"),
            "privateOrientation": obj.get("privateOrientation"),
            "ncesPrivateSchoolID": obj.get("ncesPrivateSchoolID")
        })
        return _obj


