# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from schooldigger.models.api_school_summary22 import APISchoolSummary22
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APISchoolList22(BaseModel):
    """
    APISchoolList22
    """ # noqa: E501
    number_of_schools: Optional[StrictInt] = Field(default=None, description="The total count of schools that match your query", alias="numberOfSchools")
    number_of_pages: Optional[StrictInt] = Field(default=None, description="The total count of pages in your query list based on given per_page value", alias="numberOfPages")
    school_list: Optional[List[APISchoolSummary22]] = Field(default=None, alias="schoolList")
    __properties: ClassVar[List[str]] = ["numberOfSchools", "numberOfPages", "schoolList"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APISchoolList22 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in school_list (list)
        _items = []
        if self.school_list:
            for _item_school_list in self.school_list:
                if _item_school_list:
                    _items.append(_item_school_list.to_dict())
            _dict['schoolList'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APISchoolList22 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "numberOfSchools": obj.get("numberOfSchools"),
            "numberOfPages": obj.get("numberOfPages"),
            "schoolList": [APISchoolSummary22.from_dict(_item) for _item in obj["schoolList"]] if obj.get("schoolList") is not None else None
        })
        return _obj


