# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from schooldigger.models.api_chronic_absenteeism_rate import APIChronicAbsenteeismRate
from schooldigger.models.api_county import APICounty
from schooldigger.models.api_district_sum import APIDistrictSum
from schooldigger.models.api_dropout_rate import APIDropoutRate
from schooldigger.models.api_graduation_rate import APIGraduationRate
from schooldigger.models.api_location import APILocation
from schooldigger.models.api_rank_history import APIRankHistory
from schooldigger.models.api_school_finance import APISchoolFinance
from schooldigger.models.api_school_review import APISchoolReview
from schooldigger.models.api_test_score_wrapper import APITestScoreWrapper
from schooldigger.models.api_yearly_demographics import APIYearlyDemographics
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APISchoolFull22(BaseModel):
    """
    APISchoolFull22
    """ # noqa: E501
    schoolid: Optional[StrictStr] = Field(default=None, description="SchoolDigger School ID Number (12 digits)")
    school_name: Optional[StrictStr] = Field(default=None, description="School name", alias="schoolName")
    phone: Optional[StrictStr] = Field(default=None, description="School phone number")
    url: Optional[StrictStr] = Field(default=None, description="URL of the school's own public website (may be null if not available). This is NOT the SchoolDigger page — see urlSchoolDigger for that.")
    url_school_digger: Optional[StrictStr] = Field(default=None, description="SchoolDigger URL for this school", alias="urlSchoolDigger")
    url_compare_school_digger: Optional[StrictStr] = Field(default=None, description="SchoolDigger URL for comparing this school to nearby schools", alias="urlCompareSchoolDigger")
    address: Optional[APILocation] = None
    locale: Optional[StrictStr] = Field(default=None, description="NCES urban-centric locale classification (e.g. 'City: Large', 'Suburb: Midsize', 'Rural: Fringe'). Categories: City (Large/Midsize/Small), Suburb (Large/Midsize/Small), Town (Fringe/Distant/Remote), Rural (Fringe/Distant/Remote). See https://nces.ed.gov/ccd/rural_locales.asp")
    low_grade: Optional[StrictStr] = Field(default=None, description="The low grade served by this school (PK = Prekindergarten, K = Kindergarten)", alias="lowGrade")
    high_grade: Optional[StrictStr] = Field(default=None, description="The high grade served by this school", alias="highGrade")
    school_level: Optional[StrictStr] = Field(default=None, description="The level of school (Elementary, Middle, High, Private, Alternative)", alias="schoolLevel")
    is_charter_school: Optional[StrictStr] = Field(default=None, description="Indicates if school is a charter school (Yes/No/n-a)", alias="isCharterSchool")
    is_magnet_school: Optional[StrictStr] = Field(default=None, description="Indicates if school is a magnet school (Yes/No/n-a)", alias="isMagnetSchool")
    is_virtual_school: Optional[StrictStr] = Field(default=None, description="Indicates if school is a virtual school (Yes/No/n-a)", alias="isVirtualSchool")
    is_title_i_school: Optional[StrictStr] = Field(default=None, description="Indicates if school is a Title I school (Yes/No/n-a)", alias="isTitleISchool")
    is_title_i_schoolwide_school: Optional[StrictStr] = Field(default=None, description="Indicates if a school-wide Title I school (Yes/No/n-a)", alias="isTitleISchoolwideSchool")
    is_private: Optional[StrictBool] = Field(default=None, description="Indicates if school is a private school (Yes/No)", alias="isPrivate")
    private_days: Optional[StrictInt] = Field(default=None, description="Days in the school year (private schools only)", alias="privateDays")
    private_hours: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Hours in the school day (private schools only)", alias="privateHours")
    private_has_library: Optional[StrictBool] = Field(default=None, description="Indicates if the school has a library (private schools only)", alias="privateHasLibrary")
    private_coed: Optional[StrictStr] = Field(default=None, description="Coed/Boys/Girls (private schools only)", alias="privateCoed")
    private_orientation: Optional[StrictStr] = Field(default=None, description="Affiliation of the school (private schools only)", alias="privateOrientation")
    nces_private_school_id: Optional[StrictStr] = Field(default=None, description="The NCES ID of the school (private schools only)", alias="ncesPrivateSchoolID")
    district: Optional[APIDistrictSum] = None
    county: Optional[APICounty] = None
    reviews: Optional[List[APISchoolReview]] = Field(default=None, description="User-submitted reviews from SchoolDigger.com visitors. Each review includes a star rating (1-5), comment text (HTML encoded), date, and reviewer type (parent, student, teacher, principal, citizen). Reviews are unmoderated user content.")
    finance: Optional[List[APISchoolFinance]] = Field(default=None, description="Yearly per-student spending data. Array is sorted most recent year first. spendingPerStudent is available at Pro level; detailed federal/state/local and personnel/non-personnel breakdowns require Enterprise level.")
    graduation_rates: Optional[List[APIGraduationRate]] = Field(default=None, description="4-year adjusted cohort graduation rates at school, district, and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.", alias="graduationRates")
    dropout_rates: Optional[List[APIDropoutRate]] = Field(default=None, description="Annual dropout rates at school, district, and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.", alias="dropoutRates")
    chronic_absenteeism_rates: Optional[List[APIChronicAbsenteeismRate]] = Field(default=None, description="Chronic absenteeism rates (students missing 15+ days) at school, district, and state levels (Pro and Enterprise API level only). Array is sorted most recent year first. Data availability varies by state.", alias="chronicAbsenteeismRates")
    rank_history: Optional[List[APIRankHistory]] = Field(default=None, description="SchoolDigger yearly rank history for this school, sorted most recent year first. Schools are ranked within their state and level (Elementary, Middle, or High). Includes all available years — the full record returns more years than the summary in search results.", alias="rankHistory")
    rank_movement: Optional[StrictInt] = Field(default=None, description="Returns the movement of rank for this school between current and previous year", alias="rankMovement")
    test_scores: Optional[List[APITestScoreWrapper]] = Field(default=None, description="Standardized test score results with school, district, and state comparisons. Each entry represents one test/subject/grade/year combination. Includes percent meeting standard and optional tier breakdowns (Enterprise level). Tests are state-specific (e.g. SBA, WCAS in WA; CAASPP in CA). Requires Pro or Enterprise API subscription.", alias="testScores")
    school_yearly_details: Optional[List[APIYearlyDemographics]] = Field(default=None, description="Yearly enrollment, demographics, and staffing for this school. Array is sorted most recent year first and includes all available years (back to 1988 for some schools). The full record returns more years than the summary in search results.", alias="schoolYearlyDetails")
    __properties: ClassVar[List[str]] = ["schoolid", "schoolName", "phone", "url", "urlSchoolDigger", "urlCompareSchoolDigger", "address", "locale", "lowGrade", "highGrade", "schoolLevel", "isCharterSchool", "isMagnetSchool", "isVirtualSchool", "isTitleISchool", "isTitleISchoolwideSchool", "isPrivate", "privateDays", "privateHours", "privateHasLibrary", "privateCoed", "privateOrientation", "ncesPrivateSchoolID", "district", "county", "reviews", "finance", "graduationRates", "dropoutRates", "chronicAbsenteeismRates", "rankHistory", "rankMovement", "testScores", "schoolYearlyDetails"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APISchoolFull22 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of district
        if self.district:
            _dict['district'] = self.district.to_dict()
        # override the default output from pydantic by calling `to_dict()` of county
        if self.county:
            _dict['county'] = self.county.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in reviews (list)
        _items = []
        if self.reviews:
            for _item_reviews in self.reviews:
                if _item_reviews:
                    _items.append(_item_reviews.to_dict())
            _dict['reviews'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in finance (list)
        _items = []
        if self.finance:
            for _item_finance in self.finance:
                if _item_finance:
                    _items.append(_item_finance.to_dict())
            _dict['finance'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in graduation_rates (list)
        _items = []
        if self.graduation_rates:
            for _item_graduation_rates in self.graduation_rates:
                if _item_graduation_rates:
                    _items.append(_item_graduation_rates.to_dict())
            _dict['graduationRates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in dropout_rates (list)
        _items = []
        if self.dropout_rates:
            for _item_dropout_rates in self.dropout_rates:
                if _item_dropout_rates:
                    _items.append(_item_dropout_rates.to_dict())
            _dict['dropoutRates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in chronic_absenteeism_rates (list)
        _items = []
        if self.chronic_absenteeism_rates:
            for _item_chronic_absenteeism_rates in self.chronic_absenteeism_rates:
                if _item_chronic_absenteeism_rates:
                    _items.append(_item_chronic_absenteeism_rates.to_dict())
            _dict['chronicAbsenteeismRates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rank_history (list)
        _items = []
        if self.rank_history:
            for _item_rank_history in self.rank_history:
                if _item_rank_history:
                    _items.append(_item_rank_history.to_dict())
            _dict['rankHistory'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in test_scores (list)
        _items = []
        if self.test_scores:
            for _item_test_scores in self.test_scores:
                if _item_test_scores:
                    _items.append(_item_test_scores.to_dict())
            _dict['testScores'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in school_yearly_details (list)
        _items = []
        if self.school_yearly_details:
            for _item_school_yearly_details in self.school_yearly_details:
                if _item_school_yearly_details:
                    _items.append(_item_school_yearly_details.to_dict())
            _dict['schoolYearlyDetails'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APISchoolFull22 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schoolid": obj.get("schoolid"),
            "schoolName": obj.get("schoolName"),
            "phone": obj.get("phone"),
            "url": obj.get("url"),
            "urlSchoolDigger": obj.get("urlSchoolDigger"),
            "urlCompareSchoolDigger": obj.get("urlCompareSchoolDigger"),
            "address": APILocation.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "locale": obj.get("locale"),
            "lowGrade": obj.get("lowGrade"),
            "highGrade": obj.get("highGrade"),
            "schoolLevel": obj.get("schoolLevel"),
            "isCharterSchool": obj.get("isCharterSchool"),
            "isMagnetSchool": obj.get("isMagnetSchool"),
            "isVirtualSchool": obj.get("isVirtualSchool"),
            "isTitleISchool": obj.get("isTitleISchool"),
            "isTitleISchoolwideSchool": obj.get("isTitleISchoolwideSchool"),
            "isPrivate": obj.get("isPrivate"),
            "privateDays": obj.get("privateDays"),
            "privateHours": obj.get("privateHours"),
            "privateHasLibrary": obj.get("privateHasLibrary"),
            "privateCoed": obj.get("privateCoed"),
            "privateOrientation": obj.get("privateOrientation"),
            "ncesPrivateSchoolID": obj.get("ncesPrivateSchoolID"),
            "district": APIDistrictSum.from_dict(obj["district"]) if obj.get("district") is not None else None,
            "county": APICounty.from_dict(obj["county"]) if obj.get("county") is not None else None,
            "reviews": [APISchoolReview.from_dict(_item) for _item in obj["reviews"]] if obj.get("reviews") is not None else None,
            "finance": [APISchoolFinance.from_dict(_item) for _item in obj["finance"]] if obj.get("finance") is not None else None,
            "graduationRates": [APIGraduationRate.from_dict(_item) for _item in obj["graduationRates"]] if obj.get("graduationRates") is not None else None,
            "dropoutRates": [APIDropoutRate.from_dict(_item) for _item in obj["dropoutRates"]] if obj.get("dropoutRates") is not None else None,
            "chronicAbsenteeismRates": [APIChronicAbsenteeismRate.from_dict(_item) for _item in obj["chronicAbsenteeismRates"]] if obj.get("chronicAbsenteeismRates") is not None else None,
            "rankHistory": [APIRankHistory.from_dict(_item) for _item in obj["rankHistory"]] if obj.get("rankHistory") is not None else None,
            "rankMovement": obj.get("rankMovement"),
            "testScores": [APITestScoreWrapper.from_dict(_item) for _item in obj["testScores"]] if obj.get("testScores") is not None else None,
            "schoolYearlyDetails": [APIYearlyDemographics.from_dict(_item) for _item in obj["schoolYearlyDetails"]] if obj.get("schoolYearlyDetails") is not None else None
        })
        return _obj


