# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from schooldigger.models.api_polyline import APIPolyline
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APIBoundary12(BaseModel):
    """
    APIBoundary12
    """ # noqa: E501
    polyline_collection: Optional[List[APIPolyline]] = Field(default=None, description="Collection of one or more Google Maps encoded polylines representing the attendance boundary. IMPORTANT: Polyline strings are JSON-encoded with escaped backslashes (double backslashes). You must unescape before passing to Google Maps decoding functions. Multiple polylines represent districts/schools with non-contiguous boundary areas.", alias="polylineCollection")
    polylines: Optional[StrictStr] = Field(default=None, description="Boundary as a WKT (Well-Known Text) MULTIPOLYGON string with explicit latitude/longitude vertices. Can be used directly with GIS software, PostGIS, or any system that accepts WKT geometry. Format: MULTIPOLYGON (((-122.27 47.77, ...)))")
    has_boundary: Optional[StrictBool] = Field(default=None, description="States whether there is a boundary available", alias="hasBoundary")
    __properties: ClassVar[List[str]] = ["polylineCollection", "polylines", "hasBoundary"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIBoundary12 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in polyline_collection (list)
        _items = []
        if self.polyline_collection:
            for _item_polyline_collection in self.polyline_collection:
                if _item_polyline_collection:
                    _items.append(_item_polyline_collection.to_dict())
            _dict['polylineCollection'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIBoundary12 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "polylineCollection": [APIPolyline.from_dict(_item) for _item in obj["polylineCollection"]] if obj.get("polylineCollection") is not None else None,
            "polylines": obj.get("polylines"),
            "hasBoundary": obj.get("hasBoundary")
        })
        return _obj


