# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APISchoolFinance(BaseModel):
    """
    APISchoolFinance
    """ # noqa: E501
    year: Optional[StrictInt] = Field(default=None, description="Fiscal school year using spring-year convention (e.g. 2024 = the 2023-2024 fiscal year).")
    spending_per_student: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total spending per student from all funds (Pro or Enterprise level only)", alias="spendingPerStudent")
    spending_federal_personnel: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Spending per student for Personnel at the Federal Level (Enterprise level only)", alias="spendingFederalPersonnel")
    spending_federal_non_personnel: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Spending per student for Non-personnel at the Federal Level (Enterprise level only)", alias="spendingFederalNonPersonnel")
    spending_state_local_personnel: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Spending per student for Personnel at the State and Local Level (Enterprise level only)", alias="spendingStateLocalPersonnel")
    spending_state_local_non_personnel: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Spending per student for Non-personnel at the State and Local Level (Enterprise level only)", alias="spendingStateLocalNonPersonnel")
    spending_per_student_federal: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Spending per student at the Federal Level (Enterprise level only)", alias="spendingPerStudentFederal")
    spending_per_student_state_local: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Spending per student at the State and Local Level (Enterprise level only)", alias="spendingPerStudentStateLocal")
    __properties: ClassVar[List[str]] = ["year", "spendingPerStudent", "spendingFederalPersonnel", "spendingFederalNonPersonnel", "spendingStateLocalPersonnel", "spendingStateLocalNonPersonnel", "spendingPerStudentFederal", "spendingPerStudentStateLocal"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APISchoolFinance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APISchoolFinance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "year": obj.get("year"),
            "spendingPerStudent": obj.get("spendingPerStudent"),
            "spendingFederalPersonnel": obj.get("spendingFederalPersonnel"),
            "spendingFederalNonPersonnel": obj.get("spendingFederalNonPersonnel"),
            "spendingStateLocalPersonnel": obj.get("spendingStateLocalPersonnel"),
            "spendingStateLocalNonPersonnel": obj.get("spendingStateLocalNonPersonnel"),
            "spendingPerStudentFederal": obj.get("spendingPerStudentFederal"),
            "spendingPerStudentStateLocal": obj.get("spendingPerStudentStateLocal")
        })
        return _obj


