# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from schooldigger.models.api_lat_long import APILatLong
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APILocation(BaseModel):
    """
    APILocation
    """ # noqa: E501
    lat_long: Optional[APILatLong] = Field(default=None, alias="latLong")
    street: Optional[StrictStr] = Field(default=None, description="Street address of the school or district (e.g. '18500 37th Avenue N.E.')")
    city: Optional[StrictStr] = Field(default=None, description="City where the school or district is located")
    state: Optional[StrictStr] = Field(default=None, description="Two-letter state abbreviation (e.g. 'WA')")
    state_full: Optional[StrictStr] = Field(default=None, description="Full state name (WA = Washington)", alias="stateFull")
    zip: Optional[StrictStr] = Field(default=None, description="5-digit ZIP code")
    zip4: Optional[StrictStr] = Field(default=None, description="ZIP+4 suffix (4 digits, may be empty)")
    city_url: Optional[StrictStr] = Field(default=None, description="SchoolDigger URL for schools in this city", alias="cityURL")
    zip_url: Optional[StrictStr] = Field(default=None, description="SchoolDigger URL for schools in this zip code", alias="zipURL")
    html: Optional[StrictStr] = Field(default=None, description="HTML formatted address")
    __properties: ClassVar[List[str]] = ["latLong", "street", "city", "state", "stateFull", "zip", "zip4", "cityURL", "zipURL", "html"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APILocation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of lat_long
        if self.lat_long:
            _dict['latLong'] = self.lat_long.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APILocation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "latLong": APILatLong.from_dict(obj["latLong"]) if obj.get("latLong") is not None else None,
            "street": obj.get("street"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "stateFull": obj.get("stateFull"),
            "zip": obj.get("zip"),
            "zip4": obj.get("zip4"),
            "cityURL": obj.get("cityURL"),
            "zipURL": obj.get("zipURL"),
            "html": obj.get("html")
        })
        return _obj


