# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APISchoolReview(BaseModel):
    """
    APISchoolReview
    """ # noqa: E501
    submit_date: Optional[StrictStr] = Field(default=None, description="The date the review was submitted, formatted as M/D/YYYY (e.g. '1/24/2009'). Note: single-digit months and days are not zero-padded.", alias="submitDate")
    number_of_stars: Optional[StrictInt] = Field(default=None, description="Number of stars - 1 (poor) to 5 (excellent)", alias="numberOfStars")
    comment: Optional[StrictStr] = Field(default=None, description="Free-text comment left by the reviewer. Content is HTML encoded (special characters escaped). May be empty string if reviewer only left a star rating.")
    submitted_by: Optional[StrictStr] = Field(default=None, description="Reviewer type (parent, student, teacher, principal, citizen)", alias="submittedBy")
    __properties: ClassVar[List[str]] = ["submitDate", "numberOfStars", "comment", "submittedBy"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APISchoolReview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APISchoolReview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "submitDate": obj.get("submitDate"),
            "numberOfStars": obj.get("numberOfStars"),
            "comment": obj.get("comment"),
            "submittedBy": obj.get("submittedBy")
        })
        return _obj


