# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from schooldigger.models.api_boundary12 import APIBoundary12
from schooldigger.models.api_chronic_absenteeism_rate import APIChronicAbsenteeismRate
from schooldigger.models.api_county import APICounty
from schooldigger.models.api_dropout_rate import APIDropoutRate
from schooldigger.models.api_graduation_rate import APIGraduationRate
from schooldigger.models.api_location import APILocation
from schooldigger.models.api_school_finance import APISchoolFinance
from schooldigger.models.api_test_score_wrapper import APITestScoreWrapper
from schooldigger.models.apilea_rank_history import APILEARankHistory
from schooldigger.models.apilea_yearly_detail import APILEAYearlyDetail
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APIDistrictFull21(BaseModel):
    """
    APIDistrictFull21
    """ # noqa: E501
    district_id: Optional[StrictStr] = Field(default=None, description="SchoolDigger District ID Number (7 digits)", alias="districtID")
    district_name: Optional[StrictStr] = Field(default=None, description="District name", alias="districtName")
    phone: Optional[StrictStr] = Field(default=None, description="District phone number")
    url: Optional[StrictStr] = Field(default=None, description="SchoolDigger URL for this district")
    address: Optional[APILocation] = None
    low_grade: Optional[StrictStr] = Field(default=None, description="The low grade served by this district (PK = Prekindergarten, K = Kindergarten)", alias="lowGrade")
    high_grade: Optional[StrictStr] = Field(default=None, description="The high grade served by this district", alias="highGrade")
    number_total_schools: Optional[StrictInt] = Field(default=None, alias="numberTotalSchools")
    number_primary_schools: Optional[StrictInt] = Field(default=None, alias="numberPrimarySchools")
    number_middle_schools: Optional[StrictInt] = Field(default=None, alias="numberMiddleSchools")
    number_high_schools: Optional[StrictInt] = Field(default=None, alias="numberHighSchools")
    number_alternative_schools: Optional[StrictInt] = Field(default=None, alias="numberAlternativeSchools")
    boundary: Optional[APIBoundary12] = None
    finance: Optional[List[APISchoolFinance]] = Field(default=None, description="Yearly per-student spending data. Array is sorted most recent year first. spendingPerStudent is available at Pro level; detailed federal/state/local and personnel/non-personnel breakdowns require Enterprise level.")
    graduation_rates: Optional[List[APIGraduationRate]] = Field(default=None, description="4-year adjusted cohort graduation rates at district and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.", alias="graduationRates")
    dropout_rates: Optional[List[APIDropoutRate]] = Field(default=None, description="Annual dropout rates at district and state levels (Pro and Enterprise API level only). Array is sorted most recent year first.", alias="dropoutRates")
    chronic_absenteeism_rates: Optional[List[APIChronicAbsenteeismRate]] = Field(default=None, description="Chronic absenteeism rates (students missing 15+ days) at district and state levels (Pro and Enterprise API level only). Array is sorted most recent year first. Data availability varies by state.", alias="chronicAbsenteeismRates")
    is_within_boundary: Optional[StrictBool] = Field(default=None, description="Indicates whether this district's boundary includes the specified location from nearLatitude/nearLongitude", alias="isWithinBoundary")
    county: Optional[APICounty] = None
    rank_history: Optional[List[APILEARankHistory]] = Field(default=None, description="SchoolDigger yearly rank history for this district, sorted most recent year first. Districts are ranked statewide regardless of level.", alias="rankHistory")
    district_yearly_details: Optional[List[APILEAYearlyDetail]] = Field(default=None, description="Yearly enrollment and staffing details for this district. Array is sorted most recent year first. Includes detailed FTE staffing breakdowns by role (teachers by level, administrators, counselors, librarians, support staff).", alias="districtYearlyDetails")
    test_scores: Optional[List[APITestScoreWrapper]] = Field(default=None, description="Standardized test score results with district and state comparisons. Each entry represents one test/subject/grade/year combination. District-level records do not include schoolTestScore. Requires Pro or Enterprise API subscription.", alias="testScores")
    __properties: ClassVar[List[str]] = ["districtID", "districtName", "phone", "url", "address", "lowGrade", "highGrade", "numberTotalSchools", "numberPrimarySchools", "numberMiddleSchools", "numberHighSchools", "numberAlternativeSchools", "boundary", "finance", "graduationRates", "dropoutRates", "chronicAbsenteeismRates", "isWithinBoundary", "county", "rankHistory", "districtYearlyDetails", "testScores"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIDistrictFull21 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of boundary
        if self.boundary:
            _dict['boundary'] = self.boundary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in finance (list)
        _items = []
        if self.finance:
            for _item_finance in self.finance:
                if _item_finance:
                    _items.append(_item_finance.to_dict())
            _dict['finance'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in graduation_rates (list)
        _items = []
        if self.graduation_rates:
            for _item_graduation_rates in self.graduation_rates:
                if _item_graduation_rates:
                    _items.append(_item_graduation_rates.to_dict())
            _dict['graduationRates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in dropout_rates (list)
        _items = []
        if self.dropout_rates:
            for _item_dropout_rates in self.dropout_rates:
                if _item_dropout_rates:
                    _items.append(_item_dropout_rates.to_dict())
            _dict['dropoutRates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in chronic_absenteeism_rates (list)
        _items = []
        if self.chronic_absenteeism_rates:
            for _item_chronic_absenteeism_rates in self.chronic_absenteeism_rates:
                if _item_chronic_absenteeism_rates:
                    _items.append(_item_chronic_absenteeism_rates.to_dict())
            _dict['chronicAbsenteeismRates'] = _items
        # override the default output from pydantic by calling `to_dict()` of county
        if self.county:
            _dict['county'] = self.county.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in rank_history (list)
        _items = []
        if self.rank_history:
            for _item_rank_history in self.rank_history:
                if _item_rank_history:
                    _items.append(_item_rank_history.to_dict())
            _dict['rankHistory'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in district_yearly_details (list)
        _items = []
        if self.district_yearly_details:
            for _item_district_yearly_details in self.district_yearly_details:
                if _item_district_yearly_details:
                    _items.append(_item_district_yearly_details.to_dict())
            _dict['districtYearlyDetails'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in test_scores (list)
        _items = []
        if self.test_scores:
            for _item_test_scores in self.test_scores:
                if _item_test_scores:
                    _items.append(_item_test_scores.to_dict())
            _dict['testScores'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIDistrictFull21 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "districtID": obj.get("districtID"),
            "districtName": obj.get("districtName"),
            "phone": obj.get("phone"),
            "url": obj.get("url"),
            "address": APILocation.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "lowGrade": obj.get("lowGrade"),
            "highGrade": obj.get("highGrade"),
            "numberTotalSchools": obj.get("numberTotalSchools"),
            "numberPrimarySchools": obj.get("numberPrimarySchools"),
            "numberMiddleSchools": obj.get("numberMiddleSchools"),
            "numberHighSchools": obj.get("numberHighSchools"),
            "numberAlternativeSchools": obj.get("numberAlternativeSchools"),
            "boundary": APIBoundary12.from_dict(obj["boundary"]) if obj.get("boundary") is not None else None,
            "finance": [APISchoolFinance.from_dict(_item) for _item in obj["finance"]] if obj.get("finance") is not None else None,
            "graduationRates": [APIGraduationRate.from_dict(_item) for _item in obj["graduationRates"]] if obj.get("graduationRates") is not None else None,
            "dropoutRates": [APIDropoutRate.from_dict(_item) for _item in obj["dropoutRates"]] if obj.get("dropoutRates") is not None else None,
            "chronicAbsenteeismRates": [APIChronicAbsenteeismRate.from_dict(_item) for _item in obj["chronicAbsenteeismRates"]] if obj.get("chronicAbsenteeismRates") is not None else None,
            "isWithinBoundary": obj.get("isWithinBoundary"),
            "county": APICounty.from_dict(obj["county"]) if obj.get("county") is not None else None,
            "rankHistory": [APILEARankHistory.from_dict(_item) for _item in obj["rankHistory"]] if obj.get("rankHistory") is not None else None,
            "districtYearlyDetails": [APILEAYearlyDetail.from_dict(_item) for _item in obj["districtYearlyDetails"]] if obj.get("districtYearlyDetails") is not None else None,
            "testScores": [APITestScoreWrapper.from_dict(_item) for _item in obj["testScores"]] if obj.get("testScores") is not None else None
        })
        return _obj


