# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v3.0
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from schooldigger.models.api_test_score30_percent_met_standard import APITestScore30PercentMetStandard
from schooldigger.models.api_test_score30_percent_tier1 import APITestScore30PercentTier1
from schooldigger.models.api_test_score30_percent_tier2 import APITestScore30PercentTier2
from schooldigger.models.api_test_score30_percent_tier3 import APITestScore30PercentTier3
from schooldigger.models.api_test_score30_percent_tier4 import APITestScore30PercentTier4
from schooldigger.models.api_test_score30_percent_tier5 import APITestScore30PercentTier5
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APITestScore30(BaseModel):
    """
    One test result (school, district or state level) as returned by API 3.0. Same members as the 2.4 object except  that the six percent metrics are either a plain number or an APIReportedPercent object (see that class), and a  score object is returned whenever the state reported anything - including a result that consists only of  suppressed or ranged values. Hand-written (not inherited from clsSD2testScore) because the number-or-object  union cannot come from the reflection copy the 2.4 models use.
    """ # noqa: E501
    students_eligible: Optional[StrictInt] = Field(default=None, description="Count of students eligible to take test", alias="studentsEligible")
    students_tested: Optional[StrictInt] = Field(default=None, description="Count of students tested", alias="studentsTested")
    mean_scaled_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Mean scale score", alias="meanScaledScore")
    percent_met_standard: Optional[APITestScore30PercentMetStandard] = Field(default=None, alias="percentMetStandard")
    number_met_standard: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Count of students meeting state standard", alias="numberMetStandard")
    num_tier1: Optional[StrictInt] = Field(default=None, description="Count of students performing at tier 1 (Enterprise API level only)", alias="numTier1")
    num_tier2: Optional[StrictInt] = Field(default=None, description="Count of students performing at tier 2 (Enterprise API level only)", alias="numTier2")
    num_tier3: Optional[StrictInt] = Field(default=None, description="Count of students performing at tier 3 (Enterprise API level only)", alias="numTier3")
    num_tier4: Optional[StrictInt] = Field(default=None, description="Count of students performing at tier 4 (Enterprise API level only)", alias="numTier4")
    num_tier5: Optional[StrictInt] = Field(default=None, description="Count of students performing at tier 5 (Enterprise API level only)", alias="numTier5")
    percent_tier1: Optional[APITestScore30PercentTier1] = Field(default=None, alias="percentTier1")
    percent_tier2: Optional[APITestScore30PercentTier2] = Field(default=None, alias="percentTier2")
    percent_tier3: Optional[APITestScore30PercentTier3] = Field(default=None, alias="percentTier3")
    percent_tier4: Optional[APITestScore30PercentTier4] = Field(default=None, alias="percentTier4")
    percent_tier5: Optional[APITestScore30PercentTier5] = Field(default=None, alias="percentTier5")
    __properties: ClassVar[List[str]] = ["studentsEligible", "studentsTested", "meanScaledScore", "percentMetStandard", "numberMetStandard", "numTier1", "numTier2", "numTier3", "numTier4", "numTier5", "percentTier1", "percentTier2", "percentTier3", "percentTier4", "percentTier5"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APITestScore30 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of percent_met_standard
        if self.percent_met_standard:
            _dict['percentMetStandard'] = self.percent_met_standard.to_dict()
        # override the default output from pydantic by calling `to_dict()` of percent_tier1
        if self.percent_tier1:
            _dict['percentTier1'] = self.percent_tier1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of percent_tier2
        if self.percent_tier2:
            _dict['percentTier2'] = self.percent_tier2.to_dict()
        # override the default output from pydantic by calling `to_dict()` of percent_tier3
        if self.percent_tier3:
            _dict['percentTier3'] = self.percent_tier3.to_dict()
        # override the default output from pydantic by calling `to_dict()` of percent_tier4
        if self.percent_tier4:
            _dict['percentTier4'] = self.percent_tier4.to_dict()
        # override the default output from pydantic by calling `to_dict()` of percent_tier5
        if self.percent_tier5:
            _dict['percentTier5'] = self.percent_tier5.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APITestScore30 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "studentsEligible": obj.get("studentsEligible"),
            "studentsTested": obj.get("studentsTested"),
            "meanScaledScore": obj.get("meanScaledScore"),
            "percentMetStandard": APITestScore30PercentMetStandard.from_dict(obj["percentMetStandard"]) if obj.get("percentMetStandard") is not None else None,
            "numberMetStandard": obj.get("numberMetStandard"),
            "numTier1": obj.get("numTier1"),
            "numTier2": obj.get("numTier2"),
            "numTier3": obj.get("numTier3"),
            "numTier4": obj.get("numTier4"),
            "numTier5": obj.get("numTier5"),
            "percentTier1": APITestScore30PercentTier1.from_dict(obj["percentTier1"]) if obj.get("percentTier1") is not None else None,
            "percentTier2": APITestScore30PercentTier2.from_dict(obj["percentTier2"]) if obj.get("percentTier2") is not None else None,
            "percentTier3": APITestScore30PercentTier3.from_dict(obj["percentTier3"]) if obj.get("percentTier3") is not None else None,
            "percentTier4": APITestScore30PercentTier4.from_dict(obj["percentTier4"]) if obj.get("percentTier4") is not None else None,
            "percentTier5": APITestScore30PercentTier5.from_dict(obj["percentTier5"]) if obj.get("percentTier5") is not None else None
        })
        return _obj


