# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from schooldigger.models.api_district_summary21 import APIDistrictSummary21
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APIDistrictListRank21(BaseModel):
    """
    APIDistrictListRank21
    """ # noqa: E501
    rank_year: Optional[StrictInt] = Field(default=None, description="Year this ranking list represents (2018 = 2017-18)", alias="rankYear")
    rank_year_compare: Optional[StrictInt] = Field(default=None, description="Year rankings returned for comparison (2018 = 2017-18)", alias="rankYearCompare")
    rank_years_available: Optional[List[StrictInt]] = Field(default=None, description="The years for which SchoolDigger district rankings are available for this state", alias="rankYearsAvailable")
    number_of_districts: Optional[StrictInt] = Field(default=None, description="The total count of districts in the entire rank list", alias="numberOfDistricts")
    number_of_pages: Optional[StrictInt] = Field(default=None, description="The total count of pages in your query list based on given per_page value", alias="numberOfPages")
    district_list: Optional[List[APIDistrictSummary21]] = Field(default=None, alias="districtList")
    rank_compare_year: Optional[StrictInt] = Field(default=None, alias="rankCompareYear")
    __properties: ClassVar[List[str]] = ["rankYear", "rankYearCompare", "rankYearsAvailable", "numberOfDistricts", "numberOfPages", "districtList", "rankCompareYear"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIDistrictListRank21 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in district_list (list)
        _items = []
        if self.district_list:
            for _item_district_list in self.district_list:
                if _item_district_list:
                    _items.append(_item_district_list.to_dict())
            _dict['districtList'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIDistrictListRank21 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rankYear": obj.get("rankYear"),
            "rankYearCompare": obj.get("rankYearCompare"),
            "rankYearsAvailable": obj.get("rankYearsAvailable"),
            "numberOfDistricts": obj.get("numberOfDistricts"),
            "numberOfPages": obj.get("numberOfPages"),
            "districtList": [APIDistrictSummary21.from_dict(_item) for _item in obj["districtList"]] if obj.get("districtList") is not None else None,
            "rankCompareYear": obj.get("rankCompareYear")
        })
        return _obj


