# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APIDistrictAC(BaseModel):
    """
    APIDistrictAC
    """ # noqa: E501
    districtid: Optional[StrictStr] = Field(default=None, description="SchoolDigger District ID Number (7 digits). Use /districts/{districtID} to retrieve the full district record")
    district_name: Optional[StrictStr] = Field(default=None, description="District name", alias="districtName")
    city: Optional[StrictStr] = Field(default=None, description="District location city")
    state: Optional[StrictStr] = Field(default=None, description="District location state")
    zip: Optional[StrictStr] = Field(default=None, description="District location zip code")
    low_grade: Optional[StrictStr] = Field(default=None, description="The low grade served by this district (PK = Prekindergarten, K = Kindergarten)", alias="lowGrade")
    high_grade: Optional[StrictStr] = Field(default=None, description="The high grade served by this district", alias="highGrade")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="District location latitude")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="District location longitude")
    has_boundary: Optional[StrictBool] = Field(default=None, description="States whether there is an attendance boundary available for this District", alias="hasBoundary")
    rank: Optional[StrictInt] = Field(default=None, description="Statewide rank of this district")
    rank_of: Optional[StrictInt] = Field(default=None, description="Count of districts ranked at this state/level", alias="rankOf")
    rank_stars: Optional[StrictInt] = Field(default=None, description="The number of stars SchoolDigger awarded in the ranking of the district (0-5, 5 is best)", alias="rankStars")
    __properties: ClassVar[List[str]] = ["districtid", "districtName", "city", "state", "zip", "lowGrade", "highGrade", "latitude", "longitude", "hasBoundary", "rank", "rankOf", "rankStars"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIDistrictAC from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIDistrictAC from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "districtid": obj.get("districtid"),
            "districtName": obj.get("districtName"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "zip": obj.get("zip"),
            "lowGrade": obj.get("lowGrade"),
            "highGrade": obj.get("highGrade"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "hasBoundary": obj.get("hasBoundary"),
            "rank": obj.get("rank"),
            "rankOf": obj.get("rankOf"),
            "rankStars": obj.get("rankStars")
        })
        return _obj


