# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.4
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from schooldigger.models.api_test_score import APITestScore
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APITestScoreWrapper(BaseModel):
    """
    APITestScoreWrapper
    """ # noqa: E501
    test: Optional[StrictStr] = Field(default=None, description="The name of the state-administered test")
    subject: Optional[StrictStr] = Field(default=None, description="Test subject")
    year: Optional[StrictInt] = Field(default=None, description="Year test was administered (2018 = 2017-18)")
    grade: Optional[StrictStr] = Field(default=None, description="Grade level for which this test score applies (e.g. '3', '5', '8', '10', 'HS')")
    school_test_score: Optional[APITestScore] = Field(default=None, alias="schoolTestScore")
    district_test_score: Optional[APITestScore] = Field(default=None, alias="districtTestScore")
    state_test_score: Optional[APITestScore] = Field(default=None, alias="stateTestScore")
    tier1: Optional[StrictStr] = Field(default=None, description="Label for the lowest performance tier on this test (e.g. 'Below Basic', 'Level 1'). Tier labels are state-specific. Enterprise API level only.")
    tier2: Optional[StrictStr] = Field(default=None, description="Label for the second performance tier (e.g. 'Basic', 'Level 2'). Enterprise API level only.")
    tier3: Optional[StrictStr] = Field(default=None, description="Label for the third performance tier (e.g. 'Proficient', 'Level 3'). Enterprise API level only.")
    tier4: Optional[StrictStr] = Field(default=None, description="Label for the fourth performance tier (e.g. 'Advanced', 'Level 4'). Enterprise API level only.")
    tier5: Optional[StrictStr] = Field(default=None, description="Label for the fifth performance tier, if applicable (e.g. 'No Score'). Not all states use 5 tiers. Enterprise API level only.")
    __properties: ClassVar[List[str]] = ["test", "subject", "year", "grade", "schoolTestScore", "districtTestScore", "stateTestScore", "tier1", "tier2", "tier3", "tier4", "tier5"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APITestScoreWrapper from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of school_test_score
        if self.school_test_score:
            _dict['schoolTestScore'] = self.school_test_score.to_dict()
        # override the default output from pydantic by calling `to_dict()` of district_test_score
        if self.district_test_score:
            _dict['districtTestScore'] = self.district_test_score.to_dict()
        # override the default output from pydantic by calling `to_dict()` of state_test_score
        if self.state_test_score:
            _dict['stateTestScore'] = self.state_test_score.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APITestScoreWrapper from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "test": obj.get("test"),
            "subject": obj.get("subject"),
            "year": obj.get("year"),
            "grade": obj.get("grade"),
            "schoolTestScore": APITestScore.from_dict(obj["schoolTestScore"]) if obj.get("schoolTestScore") is not None else None,
            "districtTestScore": APITestScore.from_dict(obj["districtTestScore"]) if obj.get("districtTestScore") is not None else None,
            "stateTestScore": APITestScore.from_dict(obj["stateTestScore"]) if obj.get("stateTestScore") is not None else None,
            "tier1": obj.get("tier1"),
            "tier2": obj.get("tier2"),
            "tier3": obj.get("tier3"),
            "tier4": obj.get("tier4"),
            "tier5": obj.get("tier5")
        })
        return _obj


