# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APIGraduationRate(BaseModel):
    """
    APIGraduationRate
    """ # noqa: E501
    year: Optional[StrictInt] = Field(default=None, description="School year using spring-year convention (e.g. 2025 = the 2024-2025 school year)")
    school_graduation_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="4-Year Graduation Rate at the School Level (Pro or Enterprise level only)", alias="schoolGraduationRate")
    district_graduation_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="4-Year Graduation Rate at the District Level (Pro or Enterprise level only)", alias="districtGraduationRate")
    state_graduation_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="4-Year Graduation Rate at the State Level (Pro or Enterprise level only)", alias="stateGraduationRate")
    __properties: ClassVar[List[str]] = ["year", "schoolGraduationRate", "districtGraduationRate", "stateGraduationRate"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIGraduationRate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIGraduationRate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "year": obj.get("year"),
            "schoolGraduationRate": obj.get("schoolGraduationRate"),
            "districtGraduationRate": obj.get("districtGraduationRate"),
            "stateGraduationRate": obj.get("stateGraduationRate")
        })
        return _obj


