# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APISchoolAC23(BaseModel):
    """
    APISchoolAC23
    """ # noqa: E501
    schoolid: Optional[StrictStr] = Field(default=None, description="SchoolDigger School ID Number (12 digits). Use /schools/{schoolID} to retrieve the full school record")
    school_name: Optional[StrictStr] = Field(default=None, description="School name", alias="schoolName")
    city: Optional[StrictStr] = Field(default=None, description="School location city")
    state: Optional[StrictStr] = Field(default=None, description="School location state")
    zip: Optional[StrictStr] = Field(default=None, description="School location zip code (Pro, Enterprise, and Autocomplete Pro levels only)")
    school_level: Optional[StrictStr] = Field(default=None, description="The level of school (Elementary, Middle, High, Private, Alternative)", alias="schoolLevel")
    low_grade: Optional[StrictStr] = Field(default=None, description="The low grade served by this school (PK = Prekindergarten, K = Kindergarten)  (Pro, Enterprise, and Autocomplete Pro levels only)", alias="lowGrade")
    high_grade: Optional[StrictStr] = Field(default=None, description="The high grade served by this school  (Pro, Enterprise, and Autocomplete Pro levels only)", alias="highGrade")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="School location latitude (Pro, Enterprise, and Autocomplete Pro levels only)")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="School location longitude (Pro, Enterprise, and Autocomplete Pro levels only)")
    rank: Optional[StrictInt] = Field(default=None, description="Statewide rank of this School  (Pro, Enterprise, and Autocomplete Pro levels only)")
    rank_of: Optional[StrictInt] = Field(default=None, description="Count of schools ranked at this state/level (Pro, Enterprise, and Autocomplete Pro levels only)", alias="rankOf")
    rank_stars: Optional[StrictInt] = Field(default=None, description="The number of stars SchoolDigger awarded in the ranking of the school (0-5, 5 is best) (Pro, Enterprise, and Autocomplete Pro levels only)", alias="rankStars")
    nces_private_school_id: Optional[StrictStr] = Field(default=None, description="The NCES ID of the school (private schools only)", alias="ncesPrivateSchoolID")
    __properties: ClassVar[List[str]] = ["schoolid", "schoolName", "city", "state", "zip", "schoolLevel", "lowGrade", "highGrade", "latitude", "longitude", "rank", "rankOf", "rankStars", "ncesPrivateSchoolID"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APISchoolAC23 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APISchoolAC23 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schoolid": obj.get("schoolid"),
            "schoolName": obj.get("schoolName"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "zip": obj.get("zip"),
            "schoolLevel": obj.get("schoolLevel"),
            "lowGrade": obj.get("lowGrade"),
            "highGrade": obj.get("highGrade"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "rank": obj.get("rank"),
            "rankOf": obj.get("rankOf"),
            "rankStars": obj.get("rankStars"),
            "ncesPrivateSchoolID": obj.get("ncesPrivateSchoolID")
        })
        return _obj


