# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v3.0
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APIReportedPercent(BaseModel):
    """
    A percent metric (percentMetStandard, percentTier1..5) that the state did not publish as a single exact number.  In API 3.0 a percent metric is EITHER a plain number (the state reported an exact value) OR this object, and is  absent when nothing was reported. status is one of: 'range' (the state published only a range: low / high are  the state's bounds), 'suppressed' (withheld by the state to protect student privacy; no value), 'legacyImputed'  (a pre-2018 SchoolDigger stand-in: value is the 4 / 96 number older API versions return, low / high are the  state's bounds), 'derived' (computed by SchoolDigger from the other reported levels: value when exact, otherwise  low / high). Rendering rule: exact 82.3 -&gt; '82.3%'; low 0 -&gt; '&lt; 10%'; high 100 -&gt; '&gt;= 95%'; otherwise  '10-15%'; suppressed -&gt; a dash. See https://developer.schooldigger.com/data-quality
    """ # noqa: E501
    status: Optional[StrictStr] = Field(default=None, description="Why there is no exact number: 'range', 'suppressed', 'legacyImputed' or 'derived'")
    value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The percent value, when one exists (status 'derived' with an exact result, or the 'legacyImputed' stand-in). Absent otherwise.")
    low: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Lower bound of the range in percent (0 means 'less than high'). Absent for 'suppressed'.")
    high: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Upper bound of the range in percent (100 means 'at least low'). Absent for 'suppressed'.")
    __properties: ClassVar[List[str]] = ["status", "value", "low", "high"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIReportedPercent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIReportedPercent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "status": obj.get("status"),
            "value": obj.get("value"),
            "low": obj.get("low"),
            "high": obj.get("high")
        })
        return _obj


