# coding: utf-8

"""
    SchoolDigger API

    K-12 school and district data for 120,000+ U.S. schools

    The version of the OpenAPI document: v2.3
    Contact: api@schooldigger.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from schooldigger.models.api_county import APICounty
from schooldigger.models.api_location import APILocation
from schooldigger.models.apilea_rank_history import APILEARankHistory
from schooldigger.models.apilea_yearly_detail import APILEAYearlyDetail
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APIDistrictSummary21(BaseModel):
    """
    APIDistrictSummary21
    """ # noqa: E501
    district_id: Optional[StrictStr] = Field(default=None, description="SchoolDigger District ID Number (7 digits). Use /districts/{districtID} to retrieve the entire district record", alias="districtID")
    district_name: Optional[StrictStr] = Field(default=None, description="District name", alias="districtName")
    phone: Optional[StrictStr] = Field(default=None, description="District phone number")
    url: Optional[StrictStr] = Field(default=None, description="SchoolDigger URL for this district")
    address: Optional[APILocation] = None
    location_is_within_boundary: Optional[StrictBool] = Field(default=None, description="Indicates whether this school's boundary includes the specified location from nearLatitude/nearLongitude or boundaryAddress (Enterprise API level)", alias="locationIsWithinBoundary")
    has_boundary: Optional[StrictBool] = Field(default=None, description="Indicates that an attendance boundary is available for this district. (To retrieve, look up district with /districts/{id})", alias="hasBoundary")
    distance: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Distance in miles from the nearLatitude/nearLongitude coordinates (only populated when proximity search parameters are provided)")
    is_within_boundary: Optional[StrictBool] = Field(default=None, description="Indicates whether this district's boundary includes the specified location from nearLatitude/nearLongitude", alias="isWithinBoundary")
    county: Optional[APICounty] = None
    low_grade: Optional[StrictStr] = Field(default=None, description="The low grade served by this district (PK = Prekindergarten, K = Kindergarten)", alias="lowGrade")
    high_grade: Optional[StrictStr] = Field(default=None, description="The high grade served by this district", alias="highGrade")
    number_total_schools: Optional[StrictInt] = Field(default=None, description="Count of schools in the district", alias="numberTotalSchools")
    number_primary_schools: Optional[StrictInt] = Field(default=None, description="Count of schools designated as primary schools", alias="numberPrimarySchools")
    number_middle_schools: Optional[StrictInt] = Field(default=None, description="Count of schools designated as middle schools", alias="numberMiddleSchools")
    number_high_schools: Optional[StrictInt] = Field(default=None, description="Count of schools designated as high schools", alias="numberHighSchools")
    number_alternative_schools: Optional[StrictInt] = Field(default=None, description="Count of schools designated as other/alternative schools", alias="numberAlternativeSchools")
    rank_history: Optional[List[APILEARankHistory]] = Field(default=None, description="SchoolDigger yearly rank history of the district", alias="rankHistory")
    district_yearly_details: Optional[List[APILEAYearlyDetail]] = Field(default=None, description="District yearly metrics", alias="districtYearlyDetails")
    __properties: ClassVar[List[str]] = ["districtID", "districtName", "phone", "url", "address", "locationIsWithinBoundary", "hasBoundary", "distance", "isWithinBoundary", "county", "lowGrade", "highGrade", "numberTotalSchools", "numberPrimarySchools", "numberMiddleSchools", "numberHighSchools", "numberAlternativeSchools", "rankHistory", "districtYearlyDetails"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIDistrictSummary21 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of county
        if self.county:
            _dict['county'] = self.county.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in rank_history (list)
        _items = []
        if self.rank_history:
            for _item_rank_history in self.rank_history:
                if _item_rank_history:
                    _items.append(_item_rank_history.to_dict())
            _dict['rankHistory'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in district_yearly_details (list)
        _items = []
        if self.district_yearly_details:
            for _item_district_yearly_details in self.district_yearly_details:
                if _item_district_yearly_details:
                    _items.append(_item_district_yearly_details.to_dict())
            _dict['districtYearlyDetails'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIDistrictSummary21 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "districtID": obj.get("districtID"),
            "districtName": obj.get("districtName"),
            "phone": obj.get("phone"),
            "url": obj.get("url"),
            "address": APILocation.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "locationIsWithinBoundary": obj.get("locationIsWithinBoundary"),
            "hasBoundary": obj.get("hasBoundary"),
            "distance": obj.get("distance"),
            "isWithinBoundary": obj.get("isWithinBoundary"),
            "county": APICounty.from_dict(obj["county"]) if obj.get("county") is not None else None,
            "lowGrade": obj.get("lowGrade"),
            "highGrade": obj.get("highGrade"),
            "numberTotalSchools": obj.get("numberTotalSchools"),
            "numberPrimarySchools": obj.get("numberPrimarySchools"),
            "numberMiddleSchools": obj.get("numberMiddleSchools"),
            "numberHighSchools": obj.get("numberHighSchools"),
            "numberAlternativeSchools": obj.get("numberAlternativeSchools"),
            "rankHistory": [APILEARankHistory.from_dict(_item) for _item in obj["rankHistory"]] if obj.get("rankHistory") is not None else None,
            "districtYearlyDetails": [APILEAYearlyDetail.from_dict(_item) for _item in obj["districtYearlyDetails"]] if obj.get("districtYearlyDetails") is not None else None
        })
        return _obj


